import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Real Indian pincodes for major serviceable cities/zones
const deliveryZones: Array<{
  pincode: string;
  city: string;
  state: string;
  estimatedDays: number;
}> = [
  // Delhi
  { pincode: '110001', city: 'New Delhi', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110002', city: 'Darya Ganj', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110003', city: 'Connaught Place', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110005', city: 'Karol Bagh', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110006', city: 'Sadar Bazar', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110007', city: 'Vivek Vihar', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110008', city: 'Gole Market', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110015', city: 'Pitam Pura', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110018', city: 'Janakpuri', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110019', city: 'Lajpat Nagar', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110020', city: 'Mehrauli', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110024', city: 'Laxmi Nagar', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110025', city: 'Jamia Nagar', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110027', city: 'Tagore Garden', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110029', city: 'Sarojini Nagar', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110034', city: 'Pitampura', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110037', city: 'Vasant Kunj', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110048', city: 'Hauz Khas', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110049', city: 'Saket', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110057', city: 'Munirka', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110058', city: 'Mayur Vihar', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110062', city: 'Defence Colony', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110070', city: 'Vasant Vihar', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110075', city: 'Dwarka', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110085', city: 'Rohini', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110092', city: 'Preet Vihar', state: 'Delhi', estimatedDays: 1 },
  { pincode: '110096', city: 'Mayur Vihar Phase 3', state: 'Delhi', estimatedDays: 1 },
  // Gurgaon
  { pincode: '122001', city: 'Gurgaon', state: 'Haryana', estimatedDays: 1 },
  { pincode: '122002', city: 'DLF Phase 1', state: 'Haryana', estimatedDays: 1 },
  { pincode: '122003', city: 'DLF Phase 2', state: 'Haryana', estimatedDays: 1 },
  { pincode: '122009', city: 'DLF Phase 3', state: 'Haryana', estimatedDays: 1 },
  { pincode: '122010', city: 'DLF Phase 4', state: 'Haryana', estimatedDays: 1 },
  { pincode: '122016', city: 'Gurgaon Sector 31', state: 'Haryana', estimatedDays: 1 },
  { pincode: '122018', city: 'Sushant Lok', state: 'Haryana', estimatedDays: 1 },
  // Faridabad
  { pincode: '121001', city: 'Faridabad', state: 'Haryana', estimatedDays: 1 },
  { pincode: '121002', city: 'Faridabad Sector 7', state: 'Haryana', estimatedDays: 1 },
  { pincode: '121003', city: 'Faridabad Sector 9', state: 'Haryana', estimatedDays: 1 },
  // Noida
  { pincode: '201301', city: 'Noida', state: 'Uttar Pradesh', estimatedDays: 1 },
  { pincode: '201302', city: 'Noida Sector 18', state: 'Uttar Pradesh', estimatedDays: 1 },
  { pincode: '201303', city: 'Noida Sector 62', state: 'Uttar Pradesh', estimatedDays: 1 },
  { pincode: '201304', city: 'Noida Sector 1', state: 'Uttar Pradesh', estimatedDays: 1 },
  { pincode: '201305', city: 'Greater Noida', state: 'Uttar Pradesh', estimatedDays: 1 },
  { pincode: '201306', city: 'Noida Sector 50', state: 'Uttar Pradesh', estimatedDays: 1 },
  { pincode: '201307', city: 'Noida Sector 78', state: 'Uttar Pradesh', estimatedDays: 1 },
  { pincode: '201308', city: 'Noida Sector 137', state: 'Uttar Pradesh', estimatedDays: 1 },
  { pincode: '201310', city: 'Noida Sector 135', state: 'Uttar Pradesh', estimatedDays: 1 },
  { pincode: '201312', city: 'Noida Sector 76', state: 'Uttar Pradesh', estimatedDays: 1 },
  { pincode: '201313', city: 'Noida Sector 100', state: 'Uttar Pradesh', estimatedDays: 1 },
  { pincode: '201315', city: 'Noida Sector 121', state: 'Uttar Pradesh', estimatedDays: 1 },
  { pincode: '201321', city: 'Noida Sector 150', state: 'Uttar Pradesh', estimatedDays: 1 },

  // Mumbai
  { pincode: '400001', city: 'Mumbai Fort', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400002', city: 'Kalbadevi', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400003', city: 'Mandvi', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400004', city: 'Girgaon', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400005', city: 'Colaba', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400007', city: 'Grant Road', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400008', city: 'Mumbai Central', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400011', city: 'Jacob Circle', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400012', city: 'Parel', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400013', city: 'Delisle Road', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400014', city: 'Dadar', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400015', city: 'Worli', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400016', city: 'Mahim', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400018', city: 'Chembur', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400019', city: 'Sion', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400020', city: 'Marine Lines', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400021', city: 'Wadala', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400022', city: 'Bandra Kurla Complex', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400024', city: 'Kurla', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400025', city: 'Prabhadevi', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400026', city: 'Cuffe Parade', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400028', city: 'Khar', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400031', city: 'Tardeo', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400034', city: 'Powai', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400050', city: 'Bandra West', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400051', city: 'Bandra East', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400053', city: 'Andheri West', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400054', city: 'Andheri East', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400057', city: 'Vile Parle West', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400058', city: 'Andheri', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400061', city: 'Goregaon West', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400062', city: 'Goregaon East', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400064', city: 'Malad West', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400066', city: 'Borivali West', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400067', city: 'Kandivali West', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400068', city: 'Kandivali East', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400069', city: 'Borivali East', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400080', city: 'Mira Road', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400101', city: 'Ghatkopar West', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400102', city: 'Ghatkopar East', state: 'Maharashtra', estimatedDays: 2 },
  // Thane
  { pincode: '400601', city: 'Thane', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400602', city: 'Thane West', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400603', city: 'Thane East', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400604', city: 'Wagle Estate', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400605', city: 'Naupada', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400606', city: 'Majiwada', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400610', city: 'Kasarvadavali', state: 'Maharashtra', estimatedDays: 2 },
  // Navi Mumbai
  { pincode: '400701', city: 'Vashi', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400702', city: 'Nerul', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400703', city: 'Belapur', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400704', city: 'Kharghar', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400706', city: 'Panvel', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400708', city: 'Ulwe', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400709', city: 'Kamothe', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400710', city: 'Turbhe', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '400711', city: 'Airoli', state: 'Maharashtra', estimatedDays: 2 },

  // Pune
  { pincode: '411001', city: 'Pune', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411002', city: 'Kasba Peth', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411004', city: 'Deccan', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411005', city: 'Sadashiv Peth', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411006', city: 'Kothrud', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411007', city: 'Aundh', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411008', city: 'Shivajinagar', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411011', city: 'Sangamvadi', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411013', city: 'Khadki', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411014', city: 'Kothrud', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411015', city: 'Pashan', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411016', city: 'NIBM', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411017', city: 'Wanowrie', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411019', city: 'Yerwada', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411020', city: 'Viman Nagar', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411021', city: 'Kharadi', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411023', city: 'Magarpatta', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411024', city: 'Hadapsar', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411026', city: 'Koregaon Park', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411028', city: 'Hadapsar Industrial', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411030', city: 'Katraj', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411033', city: 'Warje', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411038', city: 'Hinjewadi', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411039', city: 'Wakad', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411040', city: 'Akurdi', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411041', city: 'Nigdi', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411046', city: 'Chinchwad', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411047', city: 'Pimpri', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411057', city: 'Hinjewadi Phase 2', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411060', city: 'Baner', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411061', city: 'Balewadi', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '411067', city: 'Kasar Amboli', state: 'Maharashtra', estimatedDays: 2 },

  // Bengaluru
  { pincode: '560001', city: 'Bengaluru GPO', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560002', city: 'Bengaluru City', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560003', city: 'Malleswaram', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560004', city: 'Yeshwantpur', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560005', city: 'Rajajinagar', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560008', city: 'Gandhi Nagar', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560009', city: 'Richmond Town', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560011', city: 'Jayanagar', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560016', city: 'Ramamurthy Nagar', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560017', city: 'Banaswadi', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560020', city: 'Hosur Road', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560021', city: 'Nagarbhavi', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560022', city: 'Vijayanagar', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560023', city: 'Magadi Road', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560024', city: 'Bapujinagar', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560025', city: 'Hanumanthnagar', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560027', city: 'Bannerghatta Road', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560029', city: 'BTM Layout', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560032', city: 'Banashankari', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560033', city: 'Marathahalli', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560034', city: 'Koramangala', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560035', city: 'Indiranagar', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560037', city: 'Maruthi Sevanagar', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560038', city: 'Indira Nagar', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560040', city: 'Whitefield Road', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560041', city: 'Whitefield', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560042', city: 'KR Puram', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560043', city: 'Kalyan Nagar', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560044', city: 'HSR Layout', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560047', city: 'Bellandur', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560048', city: 'Mahadevapura', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560049', city: 'ITPL', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560050', city: 'Electronics City', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560055', city: 'Yelahanka', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '560058', city: 'Jakkur', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560059', city: 'Thanisandra', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560066', city: 'Whitefield ITPL', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560076', city: 'BTM 2nd Stage', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560085', city: 'Mathikere', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560087', city: 'Laggere', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560090', city: 'Rajarajeshwarinagar', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '560091', city: 'Kengeri Satellite Town', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '560100', city: 'Electronic City Phase 2', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560102', city: 'Hosa Road', state: 'Karnataka', estimatedDays: 2 },
  { pincode: '560103', city: 'Sarjapur Road', state: 'Karnataka', estimatedDays: 2 },

  // Hyderabad
  { pincode: '500001', city: 'Afzal Gunj', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500002', city: 'Gandhi Bhawan', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500003', city: 'Secunderabad', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500004', city: 'Begumpet', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500006', city: 'Abids', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500012', city: 'Barkatpura', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500016', city: 'Ameerpet', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500017', city: 'Begumpet', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500020', city: 'Khairatabad', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500022', city: 'Banjara Hills', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500025', city: 'Jubilee Hills', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500028', city: 'Mehdipatnam', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500032', city: 'Gachibowli', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500033', city: 'Financial District', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500034', city: 'Banjara Hills', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500035', city: 'Punjagutta', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500036', city: 'Yousufguda', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500037', city: 'Kondapur', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500040', city: 'Malkajgiri', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500044', city: 'Kompally', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500048', city: 'Quthbullapur', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500049', city: 'Jeedimetla', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500050', city: 'Kukatpally', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500051', city: 'KPHB Colony', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500055', city: 'Erragadda', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500058', city: 'Madhapur', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500060', city: 'Kondapur', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500062', city: 'Narsingi', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500063', city: 'Gachibowli', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500064', city: 'Lingampally', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500066', city: 'Miyapur', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500067', city: 'Bachupally', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500072', city: 'Kompally', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500081', city: 'HITEC City', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500084', city: 'Kondapur', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500089', city: 'Manikonda', state: 'Telangana', estimatedDays: 2 },
  { pincode: '500091', city: 'Shamshabad', state: 'Telangana', estimatedDays: 3 },

  // Chennai
  { pincode: '600001', city: 'Parrys', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600002', city: 'Sowcarpet', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600003', city: 'Broadway', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600004', city: 'Mylapore', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600005', city: 'Triplicane', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600006', city: 'Chepauk', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600008', city: 'Egmore', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600009', city: 'Purasawalkam', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600011', city: 'Perambur', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600013', city: 'Royapuram', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600014', city: 'Tondiarpet', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600016', city: 'Thiruvottiyur', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600017', city: 'T Nagar', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600018', city: 'Saidapet', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600020', city: 'Tondiarpet', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600024', city: 'Nungambakkam', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600026', city: 'Kodambakkam', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600027', city: 'Mogappair', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600031', city: 'Koyambedu', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600033', city: 'Mylapore', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600035', city: 'Kotturpuram', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600037', city: 'Besant Nagar', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600040', city: 'Anna Nagar', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600042', city: 'Anna Nagar East', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600044', city: 'Tirumangalam', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600046', city: 'Ambattur', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600054', city: 'Porur', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600061', city: 'Nungambakkam', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600063', city: 'Chrompet', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600064', city: 'Tambaram', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600069', city: 'Medavakkam', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600070', city: 'Pallavaram', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600073', city: 'Thoraipakkam', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600075', city: 'Sholinganallur', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600087', city: 'Manali', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600097', city: 'Perungalathur', state: 'Tamil Nadu', estimatedDays: 3 },
  { pincode: '600100', city: 'Tambaram', state: 'Tamil Nadu', estimatedDays: 3 },
  { pincode: '600107', city: 'Vandalur', state: 'Tamil Nadu', estimatedDays: 3 },
  { pincode: '600113', city: 'Sriperumbudur', state: 'Tamil Nadu', estimatedDays: 3 },
  { pincode: '600116', city: 'Sriperumbudur', state: 'Tamil Nadu', estimatedDays: 3 },
  { pincode: '600118', city: 'Oragadam', state: 'Tamil Nadu', estimatedDays: 4 },
  { pincode: '600122', city: 'Porur', state: 'Tamil Nadu', estimatedDays: 2 },
  { pincode: '600125', city: 'Porur', state: 'Tamil Nadu', estimatedDays: 2 },

  // Kolkata
  { pincode: '700001', city: 'Burrabazar', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700002', city: 'Dharmatala', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700003', city: 'Esplanade', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700006', city: 'Behala', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700008', city: 'Taltala', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700009', city: 'Entally', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700010', city: 'Beleghata', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700012', city: 'Tollygunge', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700014', city: 'Behala', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700015', city: 'New Alipore', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700016', city: 'Jadavpur', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700017', city: 'Tollygunge', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700020', city: 'Salt Lake', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700023', city: 'Dum Dum', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700026', city: 'Dum Dum', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700028', city: 'Barasat', state: 'West Bengal', estimatedDays: 3 },
  { pincode: '700031', city: 'New Barrackpore', state: 'West Bengal', estimatedDays: 3 },
  { pincode: '700032', city: 'Dum Dum Airport', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700036', city: 'Howrah', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700040', city: 'Tollygunge', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700045', city: 'Maheshtala', state: 'West Bengal', estimatedDays: 3 },
  { pincode: '700053', city: 'Barisha', state: 'West Bengal', estimatedDays: 3 },
  { pincode: '700061', city: 'Asuti', state: 'West Bengal', estimatedDays: 3 },
  { pincode: '700068', city: 'Garia', state: 'West Bengal', estimatedDays: 3 },
  { pincode: '700086', city: 'Alipore', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700091', city: 'New Town', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700092', city: 'New Town', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700101', city: 'New Town', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700105', city: 'Rajarhat', state: 'West Bengal', estimatedDays: 3 },
  { pincode: '700120', city: 'New Town', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700136', city: 'New Town', state: 'West Bengal', estimatedDays: 2 },
  { pincode: '700141', city: 'New Town', state: 'West Bengal', estimatedDays: 2 },

  // Ahmedabad
  { pincode: '380001', city: 'Ahmedabad GPO', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380002', city: 'Kalupur', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380004', city: 'Madhupura', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380006', city: 'Ellisbridge', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380007', city: 'Paldi', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380008', city: 'Maninagar', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380013', city: 'Naranpura', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380015', city: 'Navrangpura', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380019', city: 'Gurukul', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380022', city: 'Gomtipur', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380023', city: 'Bapunagar', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380026', city: 'Asarwa', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380030', city: 'Memnagar', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380033', city: 'Bodakdev', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380034', city: 'Vastrapur', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380035', city: 'Ambli', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380038', city: 'Thaltej', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380040', city: 'Naroda', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380045', city: 'Vatva', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380052', city: 'Vejalpur', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380058', city: 'Thaltej', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380059', city: 'Ghatlodia', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380060', city: 'Ranip', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '380062', city: 'Sabarmati', state: 'Gujarat', estimatedDays: 2 },

  // Jaipur
  { pincode: '302001', city: 'Jaipur GPO', state: 'Rajasthan', estimatedDays: 3 },
  { pincode: '302002', city: 'Kotwali', state: 'Rajasthan', estimatedDays: 3 },
  { pincode: '302003', city: 'Sanganeri Gate', state: 'Rajasthan', estimatedDays: 3 },
  { pincode: '302004', city: 'Bani Park', state: 'Rajasthan', estimatedDays: 3 },
  { pincode: '302005', city: 'Malviya Nagar', state: 'Rajasthan', estimatedDays: 3 },
  { pincode: '302006', city: 'Raja Park', state: 'Rajasthan', estimatedDays: 3 },
  { pincode: '302012', city: 'Malviya Nagar', state: 'Rajasthan', estimatedDays: 3 },
  { pincode: '302015', city: 'Mansarovar', state: 'Rajasthan', estimatedDays: 3 },
  { pincode: '302016', city: 'Malviya Nagar', state: 'Rajasthan', estimatedDays: 3 },
  { pincode: '302017', city: 'Malviya Nagar', state: 'Rajasthan', estimatedDays: 3 },
  { pincode: '302018', city: 'Vaishali Nagar', state: 'Rajasthan', estimatedDays: 3 },
  { pincode: '302019', city: 'Vaishali Nagar', state: 'Rajasthan', estimatedDays: 3 },
  { pincode: '302020', city: 'Malviya Nagar', state: 'Rajasthan', estimatedDays: 3 },
  { pincode: '302021', city: 'Jagatpura', state: 'Rajasthan', estimatedDays: 3 },
  { pincode: '302022', city: 'Sanganer', state: 'Rajasthan', estimatedDays: 3 },
  { pincode: '302025', city: 'Sitapura', state: 'Rajasthan', estimatedDays: 3 },
  { pincode: '302031', city: 'Sodala', state: 'Rajasthan', estimatedDays: 3 },
  { pincode: '302039', city: 'Tonk Road', state: 'Rajasthan', estimatedDays: 3 },
  { pincode: '302040', city: 'Pratap Nagar', state: 'Rajasthan', estimatedDays: 3 },
  { pincode: '302043', city: 'Jhotwara', state: 'Rajasthan', estimatedDays: 3 },
  { pincode: '302052', city: 'Mansarovar', state: 'Rajasthan', estimatedDays: 3 },

  // Lucknow
  { pincode: '226001', city: 'Hazratganj', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '226003', city: 'Aminabad', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '226004', city: 'Charbagh', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '226006', city: 'Gomti Nagar', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '226007', city: 'Aliganj', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '226010', city: 'Aliganj', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '226012', city: 'Gomti Nagar', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '226014', city: 'Indira Nagar', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '226015', city: 'Indira Nagar', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '226016', city: 'Indira Nagar', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '226017', city: 'Gomti Nagar', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '226018', city: 'Vikas Nagar', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '226020', city: 'Telibagh', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '226022', city: 'Rajajipuram', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '226025', city: 'Mahanagar', state: 'Uttar Pradesh', estimatedDays: 3 },

  // Chandigarh
  { pincode: '160001', city: 'Chandigarh GPO', state: 'Chandigarh', estimatedDays: 2 },
  { pincode: '160017', city: 'Sector 17', state: 'Chandigarh', estimatedDays: 2 },
  { pincode: '160018', city: 'Sector 18', state: 'Chandigarh', estimatedDays: 2 },
  { pincode: '160019', city: 'Sector 19', state: 'Chandigarh', estimatedDays: 2 },
  { pincode: '160022', city: 'Sector 22', state: 'Chandigarh', estimatedDays: 2 },
  { pincode: '160036', city: 'Sector 36', state: 'Chandigarh', estimatedDays: 2 },
  { pincode: '160047', city: 'Sector 47', state: 'Chandigarh', estimatedDays: 2 },
  { pincode: '160062', city: 'Sector 62', state: 'Chandigarh', estimatedDays: 2 },

  // Indore
  { pincode: '452001', city: 'Indore GPO', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '452002', city: 'Rajwada', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '452003', city: 'Vijay Nagar', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '452005', city: 'Khajrana', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '452007', city: 'Tilak Nagar', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '452008', city: 'Geeta Bhawan', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '452009', city: 'Mhow', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '452010', city: 'Saket', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '452011', city: 'Pithampur', state: 'Madhya Pradesh', estimatedDays: 4 },
  { pincode: '452012', city: 'Rajendra Nagar', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '452013', city: 'Sudama Nagar', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '452016', city: 'Pithampur Sector 1', state: 'Madhya Pradesh', estimatedDays: 4 },
  { pincode: '452018', city: 'Bicholi Mardana', state: 'Madhya Pradesh', estimatedDays: 3 },

  // Bhopal
  { pincode: '462001', city: 'Bhopal GPO', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '462002', city: 'Hamidia Road', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '462003', city: 'TT Nagar', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '462007', city: 'Arera Colony', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '462008', city: 'Shivaji Nagar', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '462010', city: 'Govindpura', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '462016', city: 'Bairagarh', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '462023', city: 'Kolar', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '462026', city: 'Berasia', state: 'Madhya Pradesh', estimatedDays: 4 },
  { pincode: '462030', city: 'Bagsewania', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '462036', city: 'BHEL', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '462038', city: 'Piplani', state: 'Madhya Pradesh', estimatedDays: 3 },
  { pincode: '462039', city: 'Rohit Nagar', state: 'Madhya Pradesh', estimatedDays: 3 },

  // Patna
  { pincode: '800001', city: 'Patna GPO', state: 'Bihar', estimatedDays: 3 },
  { pincode: '800002', city: 'Boring Road', state: 'Bihar', estimatedDays: 3 },
  { pincode: '800003', city: 'Kankarbagh', state: 'Bihar', estimatedDays: 3 },
  { pincode: '800004', city: 'Patna City', state: 'Bihar', estimatedDays: 3 },
  { pincode: '800005', city: 'Patliputra', state: 'Bihar', estimatedDays: 3 },
  { pincode: '800006', city: 'Patna Junction', state: 'Bihar', estimatedDays: 3 },
  { pincode: '800020', city: 'Patliputra', state: 'Bihar', estimatedDays: 3 },
  { pincode: '800022', city: 'Kankarbagh', state: 'Bihar', estimatedDays: 3 },
  { pincode: '800024', city: 'Anisabad', state: 'Bihar', estimatedDays: 3 },

  // Nagpur
  { pincode: '440001', city: 'Nagpur GPO', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '440002', city: 'Sadar', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '440003', city: 'Mahal', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '440007', city: 'Ramdaspeth', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '440008', city: 'Civil Lines', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '440010', city: 'Ramnagar', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '440012', city: 'Manewada', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '440013', city: 'Dharampeth', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '440015', city: 'Besa', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '440018', city: 'Trimurti Nagar', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '440022', city: 'Shivaji Nagar', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '440024', city: 'Laxminagar', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '440025', city: 'Ajni', state: 'Maharashtra', estimatedDays: 2 },
  { pincode: '440033', city: 'Butibori', state: 'Maharashtra', estimatedDays: 3 },

  // Coimbatore
  { pincode: '641001', city: 'Coimbatore GPO', state: 'Tamil Nadu', estimatedDays: 3 },
  { pincode: '641002', city: 'RS Puram', state: 'Tamil Nadu', estimatedDays: 3 },
  { pincode: '641004', city: 'Gandhipuram', state: 'Tamil Nadu', estimatedDays: 3 },
  { pincode: '641005', city: 'Ukkadam', state: 'Tamil Nadu', estimatedDays: 3 },
  { pincode: '641007', city: 'Peelamedu', state: 'Tamil Nadu', estimatedDays: 3 },
  { pincode: '641011', city: 'Peelamedu', state: 'Tamil Nadu', estimatedDays: 3 },
  { pincode: '641012', city: 'Gandhipuram', state: 'Tamil Nadu', estimatedDays: 3 },
  { pincode: '641014', city: 'Vadavalli', state: 'Tamil Nadu', estimatedDays: 3 },
  { pincode: '641020', city: 'Saravanampatti', state: 'Tamil Nadu', estimatedDays: 3 },
  { pincode: '641027', city: 'Thudiyalur', state: 'Tamil Nadu', estimatedDays: 3 },
  { pincode: '641035', city: 'Perur', state: 'Tamil Nadu', estimatedDays: 3 },
  { pincode: '641601', city: 'Tiruppur', state: 'Tamil Nadu', estimatedDays: 4 },
  { pincode: '641602', city: 'Tiruppur', state: 'Tamil Nadu', estimatedDays: 4 },
  { pincode: '641652', city: 'Palladam', state: 'Tamil Nadu', estimatedDays: 4 },

  // Kochi / Ernakulam
  { pincode: '682001', city: 'Kochi GPO', state: 'Kerala', estimatedDays: 3 },
  { pincode: '682011', city: 'Ernakulam', state: 'Kerala', estimatedDays: 3 },
  { pincode: '682019', city: 'Kakkanad', state: 'Kerala', estimatedDays: 3 },
  { pincode: '682025', city: 'Edappally', state: 'Kerala', estimatedDays: 3 },
  { pincode: '682035', city: 'Edappally', state: 'Kerala', estimatedDays: 3 },
  { pincode: '682041', city: 'Aluva', state: 'Kerala', estimatedDays: 3 },
  { pincode: '682050', city: 'Kakkanad', state: 'Kerala', estimatedDays: 3 },
  { pincode: '682051', city: 'Tripunithura', state: 'Kerala', estimatedDays: 3 },
  { pincode: '683001', city: 'Aluva', state: 'Kerala', estimatedDays: 3 },
  { pincode: '683101', city: 'Aluva', state: 'Kerala', estimatedDays: 3 },
  { pincode: '683501', city: 'Ernakulam', state: 'Kerala', estimatedDays: 3 },

  // Surat
  { pincode: '395001', city: 'Surat GPO', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '395002', city: 'Salabatpura', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '395003', city: 'Begampura', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '395004', city: 'Sagrampura', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '395005', city: 'Nanpura', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '395006', city: 'Vesu', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '395007', city: 'Athwa', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '395009', city: 'Adajan', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '395010', city: 'Piplod', state: 'Gujarat', estimatedDays: 2 },
  { pincode: '395017', city: 'Varachha', state: 'Gujarat', estimatedDays: 2 },

  // Visakhapatnam
  { pincode: '530001', city: 'Visakhapatnam GPO', state: 'Andhra Pradesh', estimatedDays: 3 },
  { pincode: '530002', city: 'MVP Colony', state: 'Andhra Pradesh', estimatedDays: 3 },
  { pincode: '530003', city: 'Dwaraka Nagar', state: 'Andhra Pradesh', estimatedDays: 3 },
  { pincode: '530011', city: 'Waltair', state: 'Andhra Pradesh', estimatedDays: 3 },
  { pincode: '530012', city: 'Gajuwaka', state: 'Andhra Pradesh', estimatedDays: 3 },
  { pincode: '530016', city: 'Madhurawada', state: 'Andhra Pradesh', estimatedDays: 3 },
  { pincode: '530017', city: 'Gopalapatnam', state: 'Andhra Pradesh', estimatedDays: 3 },
  { pincode: '530020', city: 'Aganampudi', state: 'Andhra Pradesh', estimatedDays: 3 },

  // Kanpur
  { pincode: '208001', city: 'Kanpur Cantt', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '208002', city: 'Kanpur GPO', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '208003', city: 'Gwaltoli', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '208004', city: 'Civil Lines', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '208005', city: 'Naya Ganj', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '208012', city: 'Kakadeo', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '208014', city: 'Govind Nagar', state: 'Uttar Pradesh', estimatedDays: 3 },
  { pincode: '208020', city: 'Panki', state: 'Uttar Pradesh', estimatedDays: 3 },

  // Mysuru
  { pincode: '570001', city: 'Mysuru GPO', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '570002', city: 'Chamundi Hills', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '570003', city: 'Vijayanagar', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '570004', city: 'Krishnamurthypuram', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '570005', city: 'Saraswatipuram', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '570006', city: 'Jayalakshmipuram', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '570008', city: 'Hebbal', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '570009', city: 'Vijayanagar 2nd Stage', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '570010', city: 'Nazarbad', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '570015', city: 'Bogadi', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '570016', city: 'Hinkal', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '570017', city: 'Srirampura', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '570020', city: 'Periyapatna', state: 'Karnataka', estimatedDays: 4 },
  { pincode: '570022', city: 'Mysuru South', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '570023', city: 'Vijayanagar 3rd Stage', state: 'Karnataka', estimatedDays: 3 },

  // Mangaluru
  { pincode: '575001', city: 'Mangaluru GPO', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '575002', city: 'Hampankatta', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '575003', city: 'Mangalore', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '575004', city: 'Kadri', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '575006', city: 'Kodialbail', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '575007', city: 'Surathkal', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '575013', city: 'Kottara', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '575014', city: 'Padil', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '575015', city: 'Konchady', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '575018', city: 'Ullal', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '575020', city: 'Bajpe', state: 'Karnataka', estimatedDays: 3 },
  { pincode: '575025', city: 'Mulki', state: 'Karnataka', estimatedDays: 3 },
];

async function main() {
  console.log('Seeding delivery zones...');
  let created = 0;
  let updated = 0;
  let skipped = 0;

  for (const zone of deliveryZones) {
    try {
      // Force isActive: true on every upsert so re-seeding activates any
      // previously-deactivated zones.
      const result = await prisma.deliveryZone.upsert({
        where: { pincode: zone.pincode },
        update: {
          city: zone.city,
          state: zone.state,
          estimatedDays: zone.estimatedDays,
          isActive: true,
          country: 'India',
        },
        create: {
          pincode: zone.pincode,
          city: zone.city,
          state: zone.state,
          country: 'India',
          estimatedDays: zone.estimatedDays,
          isActive: true,
        },
      });
      if (result.createdAt.getTime() === result.updatedAt.getTime()) {
        created++;
      } else {
        updated++;
      }
    } catch (err) {
      skipped++;
      console.error(`Failed to upsert ${zone.pincode}:`, err);
    }
  }

  // Bulk-activate any remaining inactive zones (e.g. created via admin)
  const activated = await prisma.deliveryZone.updateMany({
    where: { isActive: false },
    data: { isActive: true },
  });
  if (activated.count > 0) {
    console.log(`Bulk-activated ${activated.count} previously-inactive zones`);
  }

  const total = await prisma.deliveryZone.count();
  const active = await prisma.deliveryZone.count({ where: { isActive: true } });
  console.log(
    `Done. Created: ${created}, Updated: ${updated}, Skipped: ${skipped}, Total in DB: ${total}, Active: ${active}`,
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
