/**
 * Comprehensive list of Indian cities and towns.
 * Used by the location modal to allow the user to pick any city;
 * the system then checks if it's serviceable and shows a "coming soon"
 * message if not.
 */
export interface CityEntry {
  city: string;
  state: string;
}

export const ALL_INDIAN_CITIES: CityEntry[] = [
  // Major metros
  { city: "Mumbai", state: "Maharashtra" },
  { city: "Delhi", state: "Delhi" },
  { city: "New Delhi", state: "Delhi" },
  { city: "Bengaluru", state: "Karnataka" },
  { city: "Hyderabad", state: "Telangana" },
  { city: "Ahmedabad", state: "Gujarat" },
  { city: "Chennai", state: "Tamil Nadu" },
  { city: "Kolkata", state: "West Bengal" },
  { city: "Pune", state: "Maharashtra" },
  { city: "Jaipur", state: "Rajasthan" },
  { city: "Surat", state: "Gujarat" },
  { city: "Lucknow", state: "Uttar Pradesh" },
  { city: "Kanpur", state: "Uttar Pradesh" },
  { city: "Nagpur", state: "Maharashtra" },
  { city: "Indore", state: "Madhya Pradesh" },
  { city: "Bhopal", state: "Madhya Pradesh" },
  { city: "Patna", state: "Bihar" },
  { city: "Vadodara", state: "Gujarat" },
  { city: "Ghaziabad", state: "Uttar Pradesh" },
  { city: "Ludhiana", state: "Punjab" },
  { city: "Agra", state: "Uttar Pradesh" },
  { city: "Nashik", state: "Maharashtra" },
  { city: "Faridabad", state: "Haryana" },
  { city: "Meerut", state: "Uttar Pradesh" },
  { city: "Rajkot", state: "Gujarat" },
  { city: "Varanasi", state: "Uttar Pradesh" },
  { city: "Srinagar", state: "Jammu & Kashmir" },
  { city: "Aurangabad", state: "Maharashtra" },
  { city: "Dhanbad", state: "Jharkhand" },
  { city: "Amritsar", state: "Punjab" },
  { city: "Navi Mumbai", state: "Maharashtra" },
  { city: "Allahabad", state: "Uttar Pradesh" },
  { city: "Prayagraj", state: "Uttar Pradesh" },
  { city: "Ranchi", state: "Jharkhand" },
  { city: "Coimbatore", state: "Tamil Nadu" },
  { city: "Jabalpur", state: "Madhya Pradesh" },
  { city: "Gwalior", state: "Madhya Pradesh" },
  { city: "Vijayawada", state: "Andhra Pradesh" },
  { city: "Jodhpur", state: "Rajasthan" },
  { city: "Madurai", state: "Tamil Nadu" },
  { city: "Raipur", state: "Chhattisgarh" },
  { city: "Kota", state: "Rajasthan" },
  { city: "Guwahati", state: "Assam" },
  { city: "Chandigarh", state: "Chandigarh" },
  { city: "Thiruvananthapuram", state: "Kerala" },
  { city: "Gurugram", state: "Haryana" },
  { city: "Noida", state: "Uttar Pradesh" },
  { city: "Visakhapatnam", state: "Andhra Pradesh" },
  { city: "Mysuru", state: "Karnataka" },
  { city: "Mangaluru", state: "Karnataka" },
  { city: "Kochi", state: "Kerala" },

  // Maharashtra
  { city: "Shirdi", state: "Maharashtra" },
  { city: "Lonavala", state: "Maharashtra" },
  { city: "Khandala", state: "Maharashtra" },
  { city: "Mahabaleshwar", state: "Maharashtra" },
  { city: "Panchgani", state: "Maharashtra" },
  { city: "Matheran", state: "Maharashtra" },
  { city: "Alibag", state: "Maharashtra" },
  { city: "Murud", state: "Maharashtra" },
  { city: "Shrivardhan", state: "Maharashtra" },
  { city: "Harihareshwar", state: "Maharashtra" },
  { city: "Trimbakeshwar", state: "Maharashtra" },
  { city: "Bhimashankar", state: "Maharashtra" },
  { city: "Pandharpur", state: "Maharashtra" },
  { city: "Kolhapur", state: "Maharashtra" },
  { city: "Sangli", state: "Maharashtra" },
  { city: "Satara", state: "Maharashtra" },
  { city: "Solapur", state: "Maharashtra" },
  { city: "Latur", state: "Maharashtra" },
  { city: "Nanded", state: "Maharashtra" },
  { city: "Akola", state: "Maharashtra" },
  { city: "Amravati", state: "Maharashtra" },
  { city: "Yavatmal", state: "Maharashtra" },
  { city: "Chandrapur", state: "Maharashtra" },
  { city: "Gadchiroli", state: "Maharashtra" },
  { city: "Wardha", state: "Maharashtra" },
  { city: "Bhandara", state: "Maharashtra" },
  { city: "Gondia", state: "Maharashtra" },
  { city: "Washim", state: "Maharashtra" },
  { city: "Hingoli", state: "Maharashtra" },
  { city: "Osmanabad", state: "Maharashtra" },
  { city: "Ratnagiri", state: "Maharashtra" },
  { city: "Sindhudurg", state: "Maharashtra" },
  { city: "Sangamner", state: "Maharashtra" },
  { city: "Ahmednagar", state: "Maharashtra" },
  { city: "Jalgaon", state: "Maharashtra" },
  { city: "Dhule", state: "Maharashtra" },
  { city: "Nandurbar", state: "Maharashtra" },
  { city: "Buldhana", state: "Maharashtra" },
  { city: "Pune Camp", state: "Maharashtra" },

  // Karnataka
  { city: "Hubli", state: "Karnataka" },
  { city: "Dharwad", state: "Karnataka" },
  { city: "Belgaum", state: "Karnataka" },
  { city: "Belagavi", state: "Karnataka" },
  { city: "Gulbarga", state: "Karnataka" },
  { city: "Kalaburagi", state: "Karnataka" },
  { city: "Bijapur", state: "Karnataka" },
  { city: "Vijayapura", state: "Karnataka" },
  { city: "Shimoga", state: "Karnataka" },
  { city: "Shivamogga", state: "Karnataka" },
  { city: "Tumkur", state: "Karnataka" },
  { city: "Tumakuru", state: "Karnataka" },
  { city: "Davangere", state: "Karnataka" },
  { city: "Bellary", state: "Karnataka" },
  { city: "Ballari", state: "Karnataka" },
  { city: "Hospet", state: "Karnataka" },
  { city: "Hospete", state: "Karnataka" },
  { city: "Gadag", state: "Karnataka" },
  { city: "Haveri", state: "Karnataka" },
  { city: "Chitradurga", state: "Karnataka" },
  { city: "Kolar", state: "Karnataka" },
  { city: "Chikmagalur", state: "Karnataka" },
  { city: "Chikkamagaluru", state: "Karnataka" },
  { city: "Hassan", state: "Karnataka" },
  { city: "Mandya", state: "Karnataka" },
  { city: "Madikeri", state: "Karnataka" },
  { city: "Kodagu", state: "Karnataka" },
  { city: "Udupi", state: "Karnataka" },
  { city: "Karwar", state: "Karnataka" },
  { city: "Raichur", state: "Karnataka" },
  { city: "Bidar", state: "Karnataka" },
  { city: "Bagalkot", state: "Karnataka" },
  { city: "Chamrajnagar", state: "Karnataka" },
  { city: "Chamarajanagar", state: "Karnataka" },
  { city: "Gangavathi", state: "Karnataka" },
  { city: "Chikkaballapur", state: "Karnataka" },
  { city: "Ramanagara", state: "Karnataka" },
  { city: "Hoskote", state: "Karnataka" },
  { city: "Nelamangala", state: "Karnataka" },
  { city: "Anekal", state: "Karnataka" },
  { city: "Kanakapura", state: "Karnataka" },
  { city: "Channapatna", state: "Karnataka" },

  // Tamil Nadu
  { city: "Madurai", state: "Tamil Nadu" },
  { city: "Tiruchirappalli", state: "Tamil Nadu" },
  { city: "Trichy", state: "Tamil Nadu" },
  { city: "Salem", state: "Tamil Nadu" },
  { city: "Tirunelveli", state: "Tamil Nadu" },
  { city: "Erode", state: "Tamil Nadu" },
  { city: "Vellore", state: "Tamil Nadu" },
  { city: "Thoothukudi", state: "Tamil Nadu" },
  { city: "Tuticorin", state: "Tamil Nadu" },
  { city: "Tiruppur", state: "Tamil Nadu" },
  { city: "Tirupur", state: "Tamil Nadu" },
  { city: "Nagercoil", state: "Tamil Nadu" },
  { city: "Kanchipuram", state: "Tamil Nadu" },
  { city: "Kanchipuram", state: "Tamil Nadu" },
  { city: "Kumbakonam", state: "Tamil Nadu" },
  { city: "Thanjavur", state: "Tamil Nadu" },
  { city: "Tanjore", state: "Tamil Nadu" },
  { city: "Karur", state: "Tamil Nadu" },
  { city: "Namakkal", state: "Tamil Nadu" },
  { city: "Cuddalore", state: "Tamil Nadu" },
  { city: "Villupuram", state: "Tamil Nadu" },
  { city: "Tiruvannamalai", state: "Tamil Nadu" },
  { city: "Krishnagiri", state: "Tamil Nadu" },
  { city: "Dharmapuri", state: "Tamil Nadu" },
  { city: "Ariyalur", state: "Tamil Nadu" },
  { city: "Perambalur", state: "Tamil Nadu" },
  { city: "Virudhunagar", state: "Tamil Nadu" },
  { city: "Sivakasi", state: "Tamil Nadu" },
  { city: "Kovilpatti", state: "Tamil Nadu" },
  { city: "Rajapalayam", state: "Tamil Nadu" },
  { city: "Sankarankovil", state: "Tamil Nadu" },
  { city: "Tenkasi", state: "Tamil Nadu" },
  { city: "Ambasamudram", state: "Tamil Nadu" },
  { city: "Neyveli", state: "Tamil Nadu" },
  { city: "Panruti", state: "Tamil Nadu" },
  { city: "Chidambaram", state: "Tamil Nadu" },
  { city: "Mayiladuthurai", state: "Tamil Nadu" },
  { city: "Nagapattinam", state: "Tamil Nadu" },
  { city: "Karaikal", state: "Puducherry" },
  { city: "Puducherry", state: "Puducherry" },
  { city: "Pondicherry", state: "Puducherry" },
  { city: "Cuddalore", state: "Tamil Nadu" },
  { city: "Rameswaram", state: "Tamil Nadu" },
  { city: "Kanyakumari", state: "Tamil Nadu" },
  { city: "Kanniyakumari", state: "Tamil Nadu" },
  { city: "Hosur", state: "Tamil Nadu" },
  { city: "Krishnagiri", state: "Tamil Nadu" },
  { city: "Dindigul", state: "Tamil Nadu" },
  { city: "Palani", state: "Tamil Nadu" },
  { city: "Kodaikanal", state: "Tamil Nadu" },
  { city: "Ooty", state: "Tamil Nadu" },
  { city: "Udhagamandalam", state: "Tamil Nadu" },
  { city: "Coonoor", state: "Tamil Nadu" },
  { city: "Tiruchengode", state: "Tamil Nadu" },
  { city: "Bhavani", state: "Tamil Nadu" },
  { city: "Gobichettipalayam", state: "Tamil Nadu" },
  { city: "Mettupalayam", state: "Tamil Nadu" },
  { city: "Pollachi", state: "Tamil Nadu" },
  { city: "Udumalpet", state: "Tamil Nadu" },
  { city: "Palladam", state: "Tamil Nadu" },
  { city: "Avinashi", state: "Tamil Nadu" },
  { city: "Dharapuram", state: "Tamil Nadu" },
  { city: "Kangeyam", state: "Tamil Nadu" },
  { city: "Perundurai", state: "Tamil Nadu" },
  { city: "Bhavani Sagar", state: "Tamil Nadu" },
  { city: "Sathyamangalam", state: "Tamil Nadu" },
  { city: "Gobi", state: "Tamil Nadu" },

  // Telangana / Andhra
  { city: "Warangal", state: "Telangana" },
  { city: "Nizamabad", state: "Telangana" },
  { city: "Karimnagar", state: "Telangana" },
  { city: "Khammam", state: "Telangana" },
  { city: "Mahbubnagar", state: "Telangana" },
  { city: "Sangareddy", state: "Telangana" },
  { city: "Medak", state: "Telangana" },
  { city: "Nalgonda", state: "Telangana" },
  { city: "Adilabad", state: "Telangana" },
  { city: "Siddipet", state: "Telangana" },
  { city: "Suryapet", state: "Telangana" },
  { city: "Jagtial", state: "Telangana" },
  { city: "Mancherial", state: "Telangana" },
  { city: "Kamareddy", state: "Telangana" },
  { city: "Bhongir", state: "Telangana" },
  { city: "Tirupati", state: "Andhra Pradesh" },
  { city: "Guntur", state: "Andhra Pradesh" },
  { city: "Nellore", state: "Andhra Pradesh" },
  { city: "Kurnool", state: "Andhra Pradesh" },
  { city: "Anantapur", state: "Andhra Pradesh" },
  { city: "Kadapa", state: "Andhra Pradesh" },
  { city: "YSR Kadapa", state: "Andhra Pradesh" },
  { city: "Chittoor", state: "Andhra Pradesh" },
  { city: "Anakapalle", state: "Andhra Pradesh" },
  { city: "Eluru", state: "Andhra Pradesh" },
  { city: "Ongole", state: "Andhra Pradesh" },
  { city: "Nandyal", state: "Andhra Pradesh" },
  { city: "Machilipatnam", state: "Andhra Pradesh" },
  { city: "Tenali", state: "Andhra Pradesh" },
  { city: "Proddatur", state: "Andhra Pradesh" },
  { city: "Adoni", state: "Andhra Pradesh" },
  { city: "Hindupur", state: "Andhra Pradesh" },
  { city: "Bhimavaram", state: "Andhra Pradesh" },
  { city: "Tadepalligudem", state: "Andhra Pradesh" },
  { city: "Kakinada", state: "Andhra Pradesh" },
  { city: "Rajahmundry", state: "Andhra Pradesh" },
  { city: "Vizianagaram", state: "Andhra Pradesh" },
  { city: "Srikakulam", state: "Andhra Pradesh" },
  { city: "Vijayawada", state: "Andhra Pradesh" },
  { city: "Amaravati", state: "Andhra Pradesh" },

  // Kerala
  { city: "Kozhikode", state: "Kerala" },
  { city: "Calicut", state: "Kerala" },
  { city: "Thrissur", state: "Kerala" },
  { city: "Trichur", state: "Kerala" },
  { city: "Kollam", state: "Kerala" },
  { city: "Quilon", state: "Kerala" },
  { city: "Alappuzha", state: "Kerala" },
  { city: "Alleppey", state: "Kerala" },
  { city: "Palakkad", state: "Kerala" },
  { city: "Palghat", state: "Kerala" },
  { city: "Malappuram", state: "Kerala" },
  { city: "Manjeri", state: "Kerala" },
  { city: "Tirur", state: "Kerala" },
  { city: "Punalur", state: "Kerala" },
  { city: "Pathanamthitta", state: "Kerala" },
  { city: "Kottayam", state: "Kerala" },
  { city: "Idukki", state: "Kerala" },
  { city: "Munnar", state: "Kerala" },
  { city: "Thekkady", state: "Kerala" },
  { city: "Wayanad", state: "Kerala" },
  { city: "Kalpetta", state: "Kerala" },
  { city: "Kannur", state: "Kerala" },
  { city: "Taliparamba", state: "Kerala" },
  { city: "Thalassery", state: "Kerala" },
  { city: "Vadakara", state: "Kerala" },
  { city: "Kasaragod", state: "Kerala" },
  { city: "Kayamkulam", state: "Kerala" },
  { city: "Changanassery", state: "Kerala" },
  { city: "Pala", state: "Kerala" },
  { city: "Thodupuzha", state: "Kerala" },
  { city: "Muvattupuzha", state: "Kerala" },
  { city: "Perumbavoor", state: "Kerala" },
  { city: "Aluva", state: "Kerala" },
  { city: "Kothamangalam", state: "Kerala" },
  { city: "Vadakara", state: "Kerala" },
  { city: "Kalpetta", state: "Kerala" },

  // Gujarat
  { city: "Gandhinagar", state: "Gujarat" },
  { city: "Bharuch", state: "Gujarat" },
  { city: "Ankleshwar", state: "Gujarat" },
  { city: "Vapi", state: "Gujarat" },
  { city: "Valsad", state: "Gujarat" },
  { city: "Navsari", state: "Gujarat" },
  { city: "Silvassa", state: "Dadra & Nagar Haveli and Daman & Diu" },
  { city: "Daman", state: "Dadra & Nagar Haveli and Daman & Diu" },
  { city: "Diu", state: "Dadra & Nagar Haveli and Daman & Diu" },
  { city: "Bhavnagar", state: "Gujarat" },
  { city: "Jamnagar", state: "Gujarat" },
  { city: "Junagadh", state: "Gujarat" },
  { city: "Porbandar", state: "Gujarat" },
  { city: "Bhuj", state: "Gujarat" },
  { city: "Kutch", state: "Gujarat" },
  { city: "Gandhidham", state: "Gujarat" },
  { city: "Mundra", state: "Gujarat" },
  { city: "Adipur", state: "Gujarat" },
  { city: "Anjar", state: "Gujarat" },
  { city: "Patan", state: "Gujarat" },
  { city: "Mehsana", state: "Gujarat" },
  { city: "Palanpur", state: "Gujarat" },
  { city: "Deesa", state: "Gujarat" },
  { city: "Himmatnagar", state: "Gujarat" },
  { city: "Modasa", state: "Gujarat" },
  { city: "Godhra", state: "Gujarat" },
  { city: "Dahod", state: "Gujarat" },
  { city: "Nadiad", state: "Gujarat" },
  { city: "Anand", state: "Gujarat" },
  { city: "Kheda", state: "Gujarat" },
  { city: "Narmada", state: "Gujarat" },
  { city: "Tapi", state: "Gujarat" },
  { city: "Dang", state: "Gujarat" },
  { city: "Amreli", state: "Gujarat" },
  { city: "Botad", state: "Gujarat" },
  { city: "Morbi", state: "Gujarat" },
  { city: "Surendranagar", state: "Gujarat" },
  { city: "Dwarka", state: "Gujarat" },
  { city: "Somnath", state: "Gujarat" },
  { city: "Veraval", state: "Gujarat" },

  // Rajasthan
  { city: "Udaipur", state: "Rajasthan" },
  { city: "Jaisalmer", state: "Rajasthan" },
  { city: "Bikaner", state: "Rajasthan" },
  { city: "Ajmer", state: "Rajasthan" },
  { city: "Pushkar", state: "Rajasthan" },
  { city: "Mount Abu", state: "Rajasthan" },
  { city: "Sikar", state: "Rajasthan" },
  { city: "Alwar", state: "Rajasthan" },
  { city: "Bharatpur", state: "Rajasthan" },
  { city: "Dholpur", state: "Rajasthan" },
  { city: "Tonk", state: "Rajasthan" },
  { city: "Sawai Madhopur", state: "Rajasthan" },
  { city: "Ranthambore", state: "Rajasthan" },
  { city: "Chittorgarh", state: "Rajasthan" },
  { city: "Chittaur", state: "Rajasthan" },
  { city: "Bhilwara", state: "Rajasthan" },
  { city: "Beawar", state: "Rajasthan" },
  { city: "Pali", state: "Rajasthan" },
  { city: "Barmer", state: "Rajasthan" },
  { city: "Balotra", state: "Rajasthan" },
  { city: "Sirohi", state: "Rajasthan" },
  { city: "Mount Abu", state: "Rajasthan" },
  { city: "Pindwara", state: "Rajasthan" },
  { city: "Abu Road", state: "Rajasthan" },
  { city: "Dungarpur", state: "Rajasthan" },
  { city: "Banswara", state: "Rajasthan" },
  { city: "Pratapgarh", state: "Rajasthan" },
  { city: "Rajsamand", state: "Rajasthan" },
  { city: "Nathdwara", state: "Rajasthan" },
  { city: "Bundi", state: "Rajasthan" },
  { city: "Jhalawar", state: "Rajasthan" },
  { city: "Baran", state: "Rajasthan" },
  { city: "Behror", state: "Rajasthan" },
  { city: "Khetri", state: "Rajasthan" },
  { city: "Neem Ka Thana", state: "Rajasthan" },
  { city: "Churu", state: "Rajasthan" },
  { city: "Jhunjhunu", state: "Rajasthan" },
  { city: "Nawalgarh", state: "Rajasthan" },
  { city: "Sikar", state: "Rajasthan" },
  { city: "Bhiwadi", state: "Rajasthan" },
  { city: "Kishangarh", state: "Rajasthan" },
  { city: "Makrana", state: "Rajasthan" },

  // UP
  { city: "Agra", state: "Uttar Pradesh" },
  { city: "Mathura", state: "Uttar Pradesh" },
  { city: "Vrindavan", state: "Uttar Pradesh" },
  { city: "Aligarh", state: "Uttar Pradesh" },
  { city: "Hathras", state: "Uttar Pradesh" },
  { city: "Etah", state: "Uttar Pradesh" },
  { city: "Firozabad", state: "Uttar Pradesh" },
  { city: "Mainpuri", state: "Uttar Pradesh" },
  { city: "Etawah", state: "Uttar Pradesh" },
  { city: "Auraiya", state: "Uttar Pradesh" },
  { city: "Kanpur Dehat", state: "Uttar Pradesh" },
  { city: "Kannauj", state: "Uttar Pradesh" },
  { city: "Farrukhabad", state: "Uttar Pradesh" },
  { city: "Fatehpur", state: "Uttar Pradesh" },
  { city: "Hamirpur", state: "Uttar Pradesh" },
  { city: "Mahoba", state: "Uttar Pradesh" },
  { city: "Banda", state: "Uttar Pradesh" },
  { city: "Chitrakoot", state: "Uttar Pradesh" },
  { city: "Jhansi", state: "Uttar Pradesh" },
  { city: "Lalitpur", state: "Uttar Pradesh" },
  { city: "Jalaun", state: "Uttar Pradesh" },
  { city: "Orai", state: "Uttar Pradesh" },
  { city: "Unnao", state: "Uttar Pradesh" },
  { city: "Hardoi", state: "Uttar Pradesh" },
  { city: "Sitapur", state: "Uttar Pradesh" },
  { city: "Lakhimpur Kheri", state: "Uttar Pradesh" },
  { city: "Bahraich", state: "Uttar Pradesh" },
  { city: "Shravasti", state: "Uttar Pradesh" },
  { city: "Balrampur", state: "Uttar Pradesh" },
  { city: "Gonda", state: "Uttar Pradesh" },
  { city: "Barabanki", state: "Uttar Pradesh" },
  { city: "Faizabad", state: "Uttar Pradesh" },
  { city: "Ayodhya", state: "Uttar Pradesh" },
  { city: "Sultanpur", state: "Uttar Pradesh" },
  { city: "Amethi", state: "Uttar Pradesh" },
  { city: "Pratapgarh", state: "Uttar Pradesh" },
  { city: "Kaushambi", state: "Uttar Pradesh" },
  { city: "Azamgarh", state: "Uttar Pradesh" },
  { city: "Mau", state: "Uttar Pradesh" },
  { city: "Ballia", state: "Uttar Pradesh" },
  { city: "Jaunpur", state: "Uttar Pradesh" },
  { city: "Ghazipur", state: "Uttar Pradesh" },
  { city: "Chandauli", state: "Uttar Pradesh" },
  { city: "Sonbhadra", state: "Uttar Pradesh" },
  { city: "Mirzapur", state: "Uttar Pradesh" },
  { city: "Bhadohi", state: "Uttar Pradesh" },
  { city: "Sultanpur", state: "Uttar Pradesh" },
  { city: "Ambedkar Nagar", state: "Uttar Pradesh" },
  { city: "Basti", state: "Uttar Pradesh" },
  { city: "Sant Kabir Nagar", state: "Uttar Pradesh" },
  { city: "Siddharthnagar", state: "Uttar Pradesh" },
  { city: "Maharajganj", state: "Uttar Pradesh" },
  { city: "Kushinagar", state: "Uttar Pradesh" },
  { city: "Deoria", state: "Uttar Pradesh" },
  { city: "Gorakhpur", state: "Uttar Pradesh" },
  { city: "Basti", state: "Uttar Pradesh" },
  { city: "Sant Kabir Nagar", state: "Uttar Pradesh" },
  { city: "Siddharthnagar", state: "Uttar Pradesh" },
  { city: "Maharajganj", state: "Uttar Pradesh" },
  { city: "Bareilly", state: "Uttar Pradesh" },
  { city: "Pilibhit", state: "Uttar Pradesh" },
  { city: "Shahjahanpur", state: "Uttar Pradesh" },
  { city: "Budaun", state: "Uttar Pradesh" },
  { city: "Moradabad", state: "Uttar Pradesh" },
  { city: "Rampur", state: "Uttar Pradesh" },
  { city: "Amroha", state: "Uttar Pradesh" },
  { city: "Sambhal", state: "Uttar Pradesh" },
  { city: "Bijnor", state: "Uttar Pradesh" },
  { city: "Muzaffarnagar", state: "Uttar Pradesh" },
  { city: "Saharanpur", state: "Uttar Pradesh" },
  { city: "Chhutmalpur", state: "Uttar Pradesh" },
  { city: "Shamli", state: "Uttar Pradesh" },
  { city: "Hapur", state: "Uttar Pradesh" },
  { city: "Bulandshahr", state: "Uttar Pradesh" },
  { city: "Sambhal", state: "Uttar Pradesh" },
  { city: "Amroha", state: "Uttar Pradesh" },
  { city: "Baghpat", state: "Uttar Pradesh" },
  { city: "Muzaffarnagar", state: "Uttar Pradesh" },
  { city: "Saharanpur", state: "Uttar Pradesh" },
  { city: "Mukteshwar", state: "Uttarakhand" },
  { city: "Nainital", state: "Uttarakhand" },
  { city: "Mussoorie", state: "Uttarakhand" },
  { city: "Dehradun", state: "Uttarakhand" },
  { city: "Haridwar", state: "Uttarakhand" },
  { city: "Rishikesh", state: "Uttarakhand" },
  { city: "Roorkee", state: "Uttarakhand" },
  { city: "Haldwani", state: "Uttarakhand" },
  { city: "Rudrapur", state: "Uttarakhand" },
  { city: "Kashipur", state: "Uttarakhand" },
  { city: "Ramnagar", state: "Uttarakhand" },
  { city: "Almora", state: "Uttarakhand" },
  { city: "Ranikhet", state: "Uttarakhand" },
  { city: "Pithoragarh", state: "Uttarakhand" },
  { city: "Bageshwar", state: "Uttarakhand" },
  { city: "Chamoli", state: "Uttarakhand" },
  { city: "Rudraprayag", state: "Uttarakhand" },
  { city: "Tehri", state: "Uttarakhand" },
  { city: "Uttarkashi", state: "Uttarakhand" },
  { city: "Gopeshwar", state: "Uttarakhand" },
  { city: "Joshimath", state: "Uttarakhand" },
  { city: "Badrinath", state: "Uttarakhand" },
  { city: "Kedarnath", state: "Uttarakhand" },
  { city: "Gangotri", state: "Uttarakhand" },
  { city: "Yamunotri", state: "Uttarakhand" },
  { city: "Auli", state: "Uttarakhand" },
  { city: "Chopta", state: "Uttarakhand" },
  { city: "Guptkashi", state: "Uttarakhand" },

  // Dehradun district
  { city: "Raipur", state: "Uttarakhand" },
  { city: "Bhagwan Pur", state: "Uttarakhand" },
  { city: "Bhagwanpur", state: "Uttarakhand" },
  { city: "Mandawar", state: "Uttarakhand" },
  { city: "Vikasnagar", state: "Uttarakhand" },
  { city: "Herbertpur", state: "Uttarakhand" },
  { city: "Sahaspur", state: "Uttarakhand" },
  { city: "Rajpur", state: "Uttarakhand" },
  { city: "Premnagar", state: "Uttarakhand" },
  { city: "Clement Town", state: "Uttarakhand" },
  { city: "Dalanwala", state: "Uttarakhand" },
  { city: "Karanpur", state: "Uttarakhand" },
  { city: "Doiwala", state: "Uttarakhand" },
  { city: "Selaqui", state: "Uttarakhand" },
  { city: "Jhajra", state: "Uttarakhand" },
  { city: "Harrawala", state: "Uttarakhand" },
  { city: "Nanda Ki Chowki", state: "Uttarakhand" },
  { city: "Bhaniyawala", state: "Uttarakhand" },
  { city: "Mothrowala", state: "Uttarakhand" },
  { city: "Turner Road", state: "Uttarakhand" },
  { city: "Rajpur Road", state: "Uttarakhand" },
  { city: "Sahastradhara", state: "Uttarakhand" },
  { city: "Malsi", state: "Uttarakhand" },
  { city: "Chakrata", state: "Uttarakhand" },
  { city: "Lacchiwala", state: "Uttarakhand" },
  { city: "Lambidhar", state: "Uttarakhand" },
  { city: "Tons River", state: "Uttarakhand" },
  { city: "Baronwala", state: "Uttarakhand" },
  { city: "Mehuwala", state: "Uttarakhand" },
  { city: "Niranjanpur", state: "Uttarakhand" },
  { city: "Brahmapur", state: "Uttarakhand" },
  { city: "Tapovan", state: "Uttarakhand" },
  { city: "Rishikesh Road", state: "Uttarakhand" },
  { city: "Haridwar Bypass", state: "Uttarakhand" },

  // Haridwar district
  { city: "Har Ki Pauri", state: "Uttarakhand" },
  { city: "Maya Devi", state: "Uttarakhand" },
  { city: "Bhimgoda", state: "Uttarakhand" },
  { city: "Kankhal", state: "Uttarakhand" },
  { city: "Shivalik Nagar", state: "Uttarakhand" },
  { city: "Jwalapur", state: "Uttarakhand" },
  { city: "Bahadarabad", state: "Uttarakhand" },
  { city: "Laksar", state: "Uttarakhand" },
  { city: "Manglaur", state: "Uttarakhand" },
  { city: "Landaura", state: "Uttarakhand" },
  { city: "Dhandera", state: "Uttarakhand" },
  { city: "Patanjali", state: "Uttarakhand" },
  { city: "SIDCUL", state: "Uttarakhand" },
  { city: "Sultanpur", state: "Uttarakhand" },
  { city: "Raisi", state: "Uttarakhand" },
  { city: "Laksari", state: "Uttarakhand" },
  { city: "Bhagwanpur", state: "Uttarakhand" },
  { city: "Chhutmalpur", state: "Uttarakhand" },
  { city: "Gadharpur", state: "Uttarakhand" },
  { city: "Roorkee", state: "Uttarakhand" },
  { city: "IIT Roorkee", state: "Uttarakhand" },
  { city: "Landhaura", state: "Uttarakhand" },
  { city: "Saliyar", state: "Uttarakhand" },
  { city: "Sultanpur Patti", state: "Uttarakhand" },
  { city: "Libberheri", state: "Uttarakhand" },
  { city: "Bhagwanpur Tanda", state: "Uttarakhand" },
  { city: "Gadarpur", state: "Uttarakhand" },
  { city: "Rudrapur", state: "Uttarakhand" },
  { city: "Pantnagar", state: "Uttarakhand" },
  { city: "Haldwani", state: "Uttarakhand" },
  { city: "Kathgodam", state: "Uttarakhand" },
  { city: "Lalkuan", state: "Uttarakhand" },
  { city: "Haldi", state: "Uttarakhand" },
  { city: "Nainital Road", state: "Uttarakhand" },
  { city: "Bazpur", state: "Uttarakhand" },
  { city: "Kashipur", state: "Uttarakhand" },
  { city: "Khatima", state: "Uttarakhand" },
  { city: "Sitarganj", state: "Uttarakhand" },
  { city: "Bajpur", state: "Uttarakhand" },
  { city: "Kichha", state: "Uttarakhand" },
  { city: "Jaspur", state: "Uttarakhand" },
  { city: "Mahua Dabra", state: "Uttarakhand" },
  { city: "Mahua Kheraganj", state: "Uttarakhand" },
  { city: "Nanakmatta", state: "Uttarakhand" },
  { city: "Majra", state: "Uttarakhand" },
  { city: "Rudrapur Sector 1", state: "Uttarakhand" },
  { city: "Rudrapur Sector 2", state: "Uttarakhand" },

  // Tehri Garhwal district
  { city: "New Tehri", state: "Uttarakhand" },
  { city: "Old Tehri", state: "Uttarakhand" },
  { city: "Tehri", state: "Uttarakhand" },
  { city: "Narendra Nagar", state: "Uttarakhand" },
  { city: "Devprayag", state: "Uttarakhand" },
  { city: "Dhanaulti", state: "Uttarakhand" },
  { city: "Kanatal", state: "Uttarakhand" },
  { city: "Chamba", state: "Uttarakhand" },
  { city: "Kirtinagar", state: "Uttarakhand" },
  { city: "Ghansali", state: "Uttarakhand" },
  { city: "Pratapnagar", state: "Uttarakhand" },
  { city: "Lambgaon", state: "Uttarakhand" },
  { city: "Thati Kathur", state: "Uttarakhand" },
  { city: "Budiyakanali", state: "Uttarakhand" },
  { city: "Madan Negi", state: "Uttarakhand" },
  { city: "Gajwan", state: "Uttarakhand" },
  { city: "Pawkhal", state: "Uttarakhand" },
  { city: "Semandidhar", state: "Uttarakhand" },
  { city: "Bhilang", state: "Uttarakhand" },
  { city: "Pilkhi", state: "Uttarakhand" },
  { city: "Khas Kudaun", state: "Uttarakhand" },
  { city: "Amni", state: "Uttarakhand" },

  // Uttarkashi district
  { city: "Uttarkashi", state: "Uttarakhand" },
  { city: "Bhatwari", state: "Uttarakhand" },
  { city: "Dunda", state: "Uttarakhand" },
  { city: "Gangotri", state: "Uttarakhand" },
  { city: "Harsil", state: "Uttarakhand" },
  { city: "Mori", state: "Uttarakhand" },
  { city: "Naugaon", state: "Uttarakhand" },
  { city: "Purola", state: "Uttarakhand" },
  { city: "Sangamchatti", state: "Uttarakhand" },
  { city: "Sukhi", state: "Uttarakhand" },
  { city: "Barkot", state: "Uttarakhand" },
  { city: "Bajpur", state: "Uttarakhand" },
  { city: "Dhanauri", state: "Uttarakhand" },
  { city: "Salra", state: "Uttarakhand" },
  { city: "Nakuri", state: "Uttarakhand" },
  { city: "Damta", state: "Uttarakhand" },
  { city: "Pujeli", state: "Uttarakhand" },
  { city: "Pala", state: "Uttarakhand" },
  { city: "Tipri", state: "Uttarakhand" },
  { city: "Gangnani", state: "Uttarakhand" },
  { city: "Joshimath", state: "Uttarakhand" },
  { city: "Badrinath", state: "Uttarakhand" },
  { city: "Govindghat", state: "Uttarakhand" },
  { city: "Hanuman Chatti", state: "Uttarakhand" },
  { city: "Mana", state: "Uttarakhand" },
  { city: "Badrinath Dham", state: "Uttarakhand" },
  { city: "Hemkund Sahib", state: "Uttarakhand" },
  { city: "Ghangaria", state: "Uttarakhand" },
  { city: "Gobind Dham", state: "Uttarakhand" },

  // Pauri Garhwal district
  { city: "Pauri", state: "Uttarakhand" },
  { city: "Srinagar", state: "Uttarakhand" },
  { city: "Kotdwar", state: "Uttarakhand" },
  { city: "Lansdowne", state: "Uttarakhand" },
  { city: "Dugadda", state: "Uttarakhand" },
  { city: "Srikot", state: "Uttarakhand" },
  { city: "Khirsu", state: "Uttarakhand" },
  { city: "Pabau", state: "Uttarakhand" },
  { city: "Bhirgukhal", state: "Uttarakhand" },
  { city: "Adhari", state: "Uttarakhand" },
  { city: "Jaiharikhal", state: "Uttarakhand" },
  { city: "Satpuli", state: "Uttarakhand" },
  { city: "Dhumakot", state: "Uttarakhand" },
  { city: "Pattisain", state: "Uttarakhand" },
  { city: "Bironkhal", state: "Uttarakhand" },
  { city: "Nainidanda", state: "Uttarakhand" },
  { city: "Rikhanikhal", state: "Uttarakhand" },
  { city: "Syunsi", state: "Uttarakhand" },
  { city: "Dhoomakot", state: "Uttarakhand" },
  { city: "Thalisain", state: "Uttarakhand" },
  { city: "Paithani", state: "Uttarakhand" },
  { city: "Bazpur", state: "Uttarakhand" },
  { city: "Chelusain", state: "Uttarakhand" },
  { city: "Baijrao", state: "Uttarakhand" },
  { city: "Jaiharikhal", state: "Uttarakhand" },
  { city: "Kaljikhal", state: "Uttarakhand" },
  { city: "Jhatri", state: "Uttarakhand" },
  { city: "Ekeshwar", state: "Uttarakhand" },
  { city: "Bezonj", state: "Uttarakhand" },
  { city: "Kanda", state: "Uttarakhand" },
  { city: "Dang", state: "Uttarakhand" },
  { city: "Gairsain", state: "Uttarakhand" },

  // Rudraprayag district
  { city: "Rudraprayag", state: "Uttarakhand" },
  { city: "Kedarnath", state: "Uttarakhand" },
  { city: "Guptkashi", state: "Uttarakhand" },
  { city: "Sonprayag", state: "Uttarakhand" },
  { city: "Ukhimath", state: "Uttarakhand" },
  { city: "Gaurikund", state: "Uttarakhand" },
  { city: "Triyuginarayan", state: "Uttarakhand" },
  { city: "Tilwara", state: "Uttarakhand" },
  { city: "Chopta", state: "Uttarakhand" },
  { city: "Tungnath", state: "Uttarakhand" },
  { city: "Chandrashila", state: "Uttarakhand" },
  { city: "Deoria Tal", state: "Uttarakhand" },
  { city: "Urgam", state: "Uttarakhand" },
  { city: "Jakholi", state: "Uttarakhand" },
  { city: "Basukedar", state: "Uttarakhand" },
  { city: "Kund", state: "Uttarakhand" },
  { city: "Khumera", state: "Uttarakhand" },
  { city: "Saterakhal", state: "Uttarakhand" },
  { city: "Bhaloon", state: "Uttarakhand" },
  { city: "Luneta", state: "Uttarakhand" },

  // Chamoli district
  { city: "Gopeshwar", state: "Uttarakhand" },
  { city: "Chamoli", state: "Uttarakhand" },
  { city: "Joshimath", state: "Uttarakhand" },
  { city: "Auli", state: "Uttarakhand" },
  { city: "Badrinath", state: "Uttarakhand" },
  { city: "Hemkund Sahib", state: "Uttarakhand" },
  { city: "Ghangaria", state: "Uttarakhand" },
  { city: "Valley of Flowers", state: "Uttarakhand" },
  { city: "Govindghat", state: "Uttarakhand" },
  { city: "Nandprayag", state: "Uttarakhand" },
  { city: "Karnaprayag", state: "Uttarakhand" },
  { city: "Pipalkoti", state: "Uttarakhand" },
  { city: "Helang", state: "Uttarakhand" },
  { city: "Gopeshwar", state: "Uttarakhand" },
  { city: "Tharali", state: "Uttarakhand" },
  { city: "Gwaldam", state: "Uttarakhand" },
  { city: "Mehalchauri", state: "Uttarakhand" },
  { city: "Devaal", state: "Uttarakhand" },
  { city: "Pokhari", state: "Uttarakhand" },
  { city: "Karanprayag", state: "Uttarakhand" },
  { city: "Dewal", state: "Uttarakhand" },
  { city: "Siron", state: "Uttarakhand" },
  { city: "Badrinath Road", state: "Uttarakhand" },
  { city: "Badrinath Highway", state: "Uttarakhand" },
  { city: "Joshimath Highway", state: "Uttarakhand" },
  { city: "Tapovan Rishikesh", state: "Uttarakhand" },
  { city: "Badrinath Dham Road", state: "Uttarakhand" },

  // Nainital district
  { city: "Nainital", state: "Uttarakhand" },
  { city: "Haldwani", state: "Uttarakhand" },
  { city: "Kathgodam", state: "Uttarakhand" },
  { city: "Rudrapur", state: "Uttarakhand" },
  { city: "Kashipur", state: "Uttarakhand" },
  { city: "Ramnagar", state: "Uttarakhand" },
  { city: "Naukuchiatal", state: "Uttarakhand" },
  { city: "Bhimtal", state: "Uttarakhand" },
  { city: "Sattal", state: "Uttarakhand" },
  { city: "Bhowali", state: "Uttarakhand" },
  { city: "Mukteshwar", state: "Uttarakhand" },
  { city: "Ramgarh", state: "Uttarakhand" },
  { city: "Kaladhungi", state: "Uttarakhand" },
  { city: "Lalkuan", state: "Uttarakhand" },
  { city: "Haldi", state: "Uttarakhand" },
  { city: "Kotabagh", state: "Uttarakhand" },
  { city: "Pangot", state: "Uttarakhand" },
  { city: "Tarikhet", state: "Uttarakhand" },
  { city: "Jeolikote", state: "Uttarakhand" },
  { city: "Bhowali", state: "Uttarakhand" },
  { city: "Kosi", state: "Uttarakhand" },
  { city: "Ramnagar Corbett", state: "Uttarakhand" },
  { city: "Mohan", state: "Uttarakhand" },
  { city: "Garjiya", state: "Uttarakhand" },
  { city: "Dhikala", state: "Uttarakhand" },
  { city: "Corbett National Park", state: "Uttarakhand" },
  { city: "Durga Mandir Haldwani", state: "Uttarakhand" },
  { city: "Banbasa", state: "Uttarakhand" },
  { city: "Tanakpur", state: "Uttarakhand" },
  { city: "Jaipur Lalkua", state: "Uttarakhand" },
  { city: "Nainital Mall", state: "Uttarakhand" },
  { city: "Tallital", state: "Uttarakhand" },
  { city: "Mallital", state: "Uttarakhand" },
  { city: "Snow View Point", state: "Uttarakhand" },
  { city: "Naina Peak", state: "Uttarakhand" },
  { city: "Tiffin Top", state: "Uttarakhand" },
  { city: "Eco Cave Garden", state: "Uttarakhand" },
  { city: "Bhimtal Lake", state: "Uttarakhand" },
  { city: "Hanumangarhi", state: "Uttarakhand" },
  { city: "Pangot Cantt", state: "Uttarakhand" },

  // Almora district
  { city: "Almora", state: "Uttarakhand" },
  { city: "Ranikhet", state: "Uttarakhand" },
  { city: "Kausani", state: "Uttarakhand" },
  { city: "Binsar", state: "Uttarakhand" },
  { city: "Dwarahat", state: "Uttarakhand" },
  { city: "Someshwar", state: "Uttarakhand" },
  { city: "Jageshwar", state: "Uttarakhand" },
  { city: "Baijnath", state: "Uttarakhand" },
  { city: "Kasar Devi", state: "Uttarakhand" },
  { city: "Bright End Corner", state: "Uttarakhand" },
  { city: "Lal Bazaar", state: "Uttarakhand" },
  { city: "Malli Bazaar", state: "Uttarakhand" },
  { city: "Dhamas", state: "Uttarakhand" },
  { city: "Chitai", state: "Uttarakhand" },
  { city: "Manan", state: "Uttarakhand" },
  { city: "Bhanoli", state: "Uttarakhand" },
  { city: "Hawalbagh", state: "Uttarakhand" },
  { city: "Tadikhet", state: "Uttarakhand" },
  { city: "Chaubatia", state: "Uttarakhand" },
  { city: "Mankameshwar", state: "Uttarakhand" },
  { city: "Nanda Devi", state: "Uttarakhand" },
  { city: "Chinakholi", state: "Uttarakhand" },
  { city: "Pathar", state: "Uttarakhand" },
  { city: "Brotia", state: "Uttarakhand" },
  { city: "Jaurasi", state: "Uttarakhand" },
  { city: "Rashila", state: "Uttarakhand" },
  { city: "Syalde", state: "Uttarakhand" },
  { city: "Talla", state: "Uttarakhand" },
  { city: "Daul", state: "Uttarakhand" },
  { city: "Bhagtola", state: "Uttarakhand" },
  { city: "Bhatkhola", state: "Uttarakhand" },
  { city: "Ladhpura", state: "Uttarakhand" },
  { city: "Malla Tajpur", state: "Uttarakhand" },
  { city: "Sigar", state: "Uttarakhand" },
  { city: "Takula", state: "Uttarakhand" },
  { city: "Talla Kunjina", state: "Uttarakhand" },
  { city: "Patala Devi", state: "Uttarakhand" },
  { city: "Mayali", state: "Uttarakhand" },
  { city: "Deghat", state: "Uttarakhand" },
  { city: "Bhikia Sain", state: "Uttarakhand" },
  { city: "Kusiyachaun", state: "Uttarakhand" },
  { city: "Bhanar Tok", state: "Uttarakhand" },

  // Bageshwar district
  { city: "Bageshwar", state: "Uttarakhand" },
  { city: "Kausani", state: "Uttarakhand" },
  { city: "Baijnath", state: "Uttarakhand" },
  { city: "Gwaldam", state: "Uttarakhand" },
  { city: "Garur", state: "Uttarakhand" },
  { city: "Kapkot", state: "Uttarakhand" },
  { city: "Kanda", state: "Uttarakhand" },
  { city: "Vijaypur", state: "Uttarakhand" },
  { city: "Bachham", state: "Uttarakhand" },
  { city: "Tons", state: "Uttarakhand" },
  { city: "Hawalbagh", state: "Uttarakhand" },
  { city: "Chhana", state: "Uttarakhand" },
  { city: "Bhanar", state: "Uttarakhand" },
  { city: "Chaknaya", state: "Uttarakhand" },
  { city: "Khetikhan", state: "Uttarakhand" },
  { city: "Rithagar", state: "Uttarakhand" },
  { city: "Bhilkot", state: "Uttarakhand" },
  { city: "Garhsiro", state: "Uttarakhand" },
  { city: "Bachhanpur", state: "Uttarakhand" },
  { city: "Dofar", state: "Uttarakhand" },
  { city: "Dungari", state: "Uttarakhand" },

  // Pithoragarh district
  { city: "Pithoragarh", state: "Uttarakhand" },
  { city: "Munsyari", state: "Uttarakhand" },
  { city: "Dharchula", state: "Uttarakhand" },
  { city: "Gangolihat", state: "Uttarakhand" },
  { city: "Berinag", state: "Uttarakhand" },
  { city: "Didihat", state: "Uttarakhand" },
  { city: "Munsiari", state: "Uttarakhand" },
  { city: "Chaukori", state: "Uttarakhand" },
  { city: "Patal Bhuvaneshwar", state: "Uttarakhand" },
  { city: "Gangar", state: "Uttarakhand" },
  { city: "Kanalichhina", state: "Uttarakhand" },
  { city: "Baluwakot", state: "Uttarakhand" },
  { city: "Quiti", state: "Uttarakhand" },
  { city: "Askot", state: "Uttarakhand" },
  { city: "Garbyang", state: "Uttarakhand" },
  { city: "Nabhi", state: "Uttarakhand" },
  { city: "Jauljibi", state: "Uttarakhand" },
  { city: "Champawat", state: "Uttarakhand" },
  { city: "Lohaghat", state: "Uttarakhand" },
  { city: "Purnagiri", state: "Uttarakhand" },
  { city: "Tanakpur", state: "Uttarakhand" },
  { city: "Abbott Mount", state: "Uttarakhand" },
  { city: "Devidhura", state: "Uttarakhand" },
  { city: "Pati", state: "Uttarakhand" },
  { city: "Barani", state: "Uttarakhand" },
  { city: "Chauramehta", state: "Uttarakhand" },
  { city: "Manar", state: "Uttarakhand" },
  { city: "Amori", state: "Uttarakhand" },
  { city: "Chandrapuri", state: "Uttarakhand" },
  { city: "Reetha", state: "Uttarakhand" },
  { city: "Pulla", state: "Uttarakhand" },
  { city: "Pithora", state: "Uttarakhand" },
  { city: "Kimtoli", state: "Uttarakhand" },
  { city: "Charchum", state: "Uttarakhand" },

  // Udham Singh Nagar district
  { city: "Rudrapur", state: "Uttarakhand" },
  { city: "Kashipur", state: "Uttarakhand" },
  { city: "Khatima", state: "Uttarakhand" },
  { city: "Sitarganj", state: "Uttarakhand" },
  { city: "Bajpur", state: "Uttarakhand" },
  { city: "Gadarpur", state: "Uttarakhand" },
  { city: "Kichha", state: "Uttarakhand" },
  { city: "Jaspur", state: "Uttarakhand" },
  { city: "Pantnagar", state: "Uttarakhand" },
  { city: "Mahua Dabra", state: "Uttarakhand" },
  { city: "Mahua Kheraganj", state: "Uttarakhand" },
  { city: "Rudrapur City", state: "Uttarakhand" },
  { city: "SIDCUL Rudrapur", state: "Uttarakhand" },
  { city: "Pantnagar University", state: "Uttarakhand" },
  { city: "Tanda Ujjain", state: "Uttarakhand" },
  { city: "Bazpur", state: "Uttarakhand" },
  { city: "Bhoora Rani", state: "Uttarakhand" },
  { city: "Kashipur Bypass", state: "Uttarakhand" },
  { city: "Kichha Road", state: "Uttarakhand" },
  { city: "Dineshpur", state: "Uttarakhand" },
  { city: "Majra", state: "Uttarakhand" },
  { city: "Mahuakhera", state: "Uttarakhand" },
  { city: "Bartanpur", state: "Uttarakhand" },
  { city: "Bazpur Industrial", state: "Uttarakhand" },
  { city: "Gadarpur Industrial", state: "Uttarakhand" },
  { city: "Rudrapur Sector 5", state: "Uttarakhand" },
  { city: "Rudrapur Sector 7", state: "Uttarakhand" },

  // Champawat district
  { city: "Champawat", state: "Uttarakhand" },
  { city: "Tanakpur", state: "Uttarakhand" },
  { city: "Lohaghat", state: "Uttarakhand" },
  { city: "Purnagiri", state: "Uttarakhand" },
  { city: "Devidhura", state: "Uttarakhand" },
  { city: "Abbott Mount", state: "Uttarakhand" },
  { city: "Baram", state: "Uttarakhand" },
  { city: "Reetha", state: "Uttarakhand" },
  { city: "Bana", state: "Uttarakhand" },
  { city: "Malli", state: "Uttarakhand" },
  { city: "Mukteshwar", state: "Uttarakhand" },
  { city: "Nihal", state: "Uttarakhand" },
  { city: "Puliyal", state: "Uttarakhand" },
  { city: "Ladhyura", state: "Uttarakhand" },
  { city: "Bhingrara", state: "Uttarakhand" },
  { city: "Manjari", state: "Uttarakhand" },
  { city: "Dugtu", state: "Uttarakhand" },
  { city: "Bapru", state: "Uttarakhand" },
  { city: "Tamli", state: "Uttarakhand" },

  // Sundries
  { city: "Mussoorie", state: "Uttarakhand" },
  { city: "Dhanaulti", state: "Uttarakhand" },
  { city: "Kanatal", state: "Uttarakhand" },
  { city: "Lansdowne", state: "Uttarakhand" },
  { city: "Patty", state: "Uttarakhand" },
  { city: "Binsar", state: "Uttarakhand" },
  { city: "Jageshwar", state: "Uttarakhand" },
  { city: "Patal Bhuvaneshwar", state: "Uttarakhand" },
  { city: "Baijnath", state: "Uttarakhand" },
  { city: "Devprayag", state: "Uttarakhand" },
  { city: "Gwaldam", state: "Uttarakhand" },

  // HP
  { city: "Shimla", state: "Himachal Pradesh" },
  { city: "Manali", state: "Himachal Pradesh" },
  { city: "Dharamshala", state: "Himachal Pradesh" },
  { city: "McLeod Ganj", state: "Himachal Pradesh" },
  { city: "Kullu", state: "Himachal Pradesh" },
  { city: "Manikaran", state: "Himachal Pradesh" },
  { city: "Kasol", state: "Himachal Pradesh" },
  { city: "Tosh", state: "Himachal Pradesh" },
  { city: "Malana", state: "Himachal Pradesh" },
  { city: "Spiti", state: "Himachal Pradesh" },
  { city: "Lahaul", state: "Himachal Pradesh" },
  { city: "Keylong", state: "Himachal Pradesh" },
  { city: "Solan", state: "Himachal Pradesh" },
  { city: "Mandi", state: "Himachal Pradesh" },
  { city: "Kullu", state: "Himachal Pradesh" },
  { city: "Bilaspur", state: "Himachal Pradesh" },
  { city: "Una", state: "Himachal Pradesh" },
  { city: "Hamirpur", state: "Himachal Pradesh" },
  { city: "Kangra", state: "Himachal Pradesh" },
  { city: "Palampur", state: "Himachal Pradesh" },
  { city: "Baijnath", state: "Himachal Pradesh" },
  { city: "Chamba", state: "Himachal Pradesh" },
  { city: "Dalhousie", state: "Himachal Pradesh" },
  { city: "Khajjiar", state: "Himachal Pradesh" },
  { city: "Kasauli", state: "Himachal Pradesh" },
  { city: "Parwanoo", state: "Himachal Pradesh" },
  { city: "Nahan", state: "Himachal Pradesh" },
  { city: "Sirmaur", state: "Himachal Pradesh" },
  { city: "Kinnaur", state: "Himachal Pradesh" },
  { city: "Kalpa", state: "Himachal Pradesh" },
  { city: "Rampur", state: "Himachal Pradesh" },
  { city: "Sarahan", state: "Himachal Pradesh" },

  // Punjab
  { city: "Jalandhar", state: "Punjab" },
  { city: "Phagwara", state: "Punjab" },
  { city: "Hoshiarpur", state: "Punjab" },
  { city: "Pathankot", state: "Punjab" },
  { city: "Gurdaspur", state: "Punjab" },
  { city: "Batala", state: "Punjab" },
  { city: "Firozpur", state: "Punjab" },
  { city: "Fazilka", state: "Punjab" },
  { city: "Abohar", state: "Punjab" },
  { city: "Sri Ganganagar", state: "Rajasthan" },
  { city: "Hanumangarh", state: "Rajasthan" },
  { city: "Moga", state: "Punjab" },
  { city: "Fazilka", state: "Punjab" },
  { city: "Zirakpur", state: "Punjab" },
  { city: "Panchkula", state: "Haryana" },
  { city: "Ambala", state: "Haryana" },
  { city: "Kurukshetra", state: "Haryana" },
  { city: "Karnal", state: "Haryana" },
  { city: "Panipat", state: "Haryana" },
  { city: "Sonipat", state: "Haryana" },
  { city: "Rohtak", state: "Haryana" },
  { city: "Hisar", state: "Haryana" },
  { city: "Hansi", state: "Haryana" },
  { city: "Sirsa", state: "Haryana" },
  { city: "Fatehabad", state: "Haryana" },
  { city: "Bhiwani", state: "Haryana" },
  { city: "Mahendragarh", state: "Haryana" },
  { city: "Rewari", state: "Haryana" },
  { city: "Narnaul", state: "Haryana" },
  { city: "Nuh", state: "Haryana" },
  { city: "Mewat", state: "Haryana" },
  { city: "Palwal", state: "Haryana" },
  { city: "Jhajjar", state: "Haryana" },
  { city: "Jind", state: "Haryana" },
  { city: "Kaithal", state: "Haryana" },
  { city: "Rewari", state: "Haryana" },
  { city: "Manesar", state: "Haryana" },
  { city: "Sohna", state: "Haryana" },
  { city: "Bahadurgarh", state: "Haryana" },
  { city: "Narnaul", state: "Haryana" },
  { city: "Nuh", state: "Haryana" },
  { city: "Firozpur Jhirka", state: "Haryana" },
  { city: "Pinjore", state: "Haryana" },
  { city: "Kalka", state: "Haryana" },
  { city: "Nalagarh", state: "Himachal Pradesh" },
  { city: "Baddi", state: "Himachal Pradesh" },
  { city: "Barotiwala", state: "Himachal Pradesh" },
  { city: "Paonta Sahib", state: "Himachal Pradesh" },
  { city: "Nahan", state: "Himachal Pradesh" },

  // J&K, Ladakh
  { city: "Jammu", state: "Jammu & Kashmir" },
  { city: "Kathua", state: "Jammu & Kashmir" },
  { city: "Samba", state: "Jammu & Kashmir" },
  { city: "Udhampur", state: "Jammu & Kashmir" },
  { city: "Reasi", state: "Jammu & Kashmir" },
  { city: "Rajouri", state: "Jammu & Kashmir" },
  { city: "Poonch", state: "Jammu & Kashmir" },
  { city: "Kupwara", state: "Jammu & Kashmir" },
  { city: "Baramulla", state: "Jammu & Kashmir" },
  { city: "Bandipora", state: "Jammu & Kashmir" },
  { city: "Ganderbal", state: "Jammu & Kashmir" },
  { city: "Budgam", state: "Jammu & Kashmir" },
  { city: "Pulwama", state: "Jammu & Kashmir" },
  { city: "Shopian", state: "Jammu & Kashmir" },
  { city: "Kulgam", state: "Jammu & Kashmir" },
  { city: "Anantnag", state: "Jammu & Kashmir" },
  { city: "Doda", state: "Jammu & Kashmir" },
  { city: "Kishtwar", state: "Jammu & Kashmir" },
  { city: "Ramban", state: "Jammu & Kashmir" },
  { city: "Leh", state: "Ladakh" },
  { city: "Kargil", state: "Ladakh" },
  { city: "Nubra", state: "Ladakh" },
  { city: "Hanle", state: "Ladakh" },
  { city: "Diskit", state: "Ladakh" },
  { city: "Padum", state: "Ladakh" },
  { city: "Zanskar", state: "Ladakh" },
  { city: "Drass", state: "Ladakh" },
  { city: "Turtuk", state: "Ladakh" },

  // North East
  { city: "Imphal", state: "Manipur" },
  { city: "Shillong", state: "Meghalaya" },
  { city: "Aizawl", state: "Mizoram" },
  { city: "Kohima", state: "Nagaland" },
  { city: "Dimapur", state: "Nagaland" },
  { city: "Mokokchung", state: "Nagaland" },
  { city: "Itanagar", state: "Arunachal Pradesh" },
  { city: "Naharlagun", state: "Arunachal Pradesh" },
  { city: "Tawang", state: "Arunachal Pradesh" },
  { city: "Bomdila", state: "Arunachal Pradesh" },
  { city: "Ziro", state: "Arunachal Pradesh" },
  { city: "Pasighat", state: "Arunachal Pradesh" },
  { city: "Along", state: "Arunachal Pradesh" },
  { city: "Tezpur", state: "Assam" },
  { city: "Jorhat", state: "Assam" },
  { city: "Dibrugarh", state: "Assam" },
  { city: "Tinsukia", state: "Assam" },
  { city: "Sivasagar", state: "Assam" },
  { city: "Nagaon", state: "Assam" },
  { city: "Karimganj", state: "Assam" },
  { city: "Silchar", state: "Assam" },
  { city: "Hailakandi", state: "Assam" },
  { city: "Bongaigaon", state: "Assam" },
  { city: "Goalpara", state: "Assam" },
  { city: "Barpeta", state: "Assam" },
  { city: "Dhubri", state: "Assam" },
  { city: "Haflong", state: "Assam" },
  { city: "Diphu", state: "Assam" },
  { city: "Itanagar", state: "Arunachal Pradesh" },
  { city: "Agartala", state: "Tripura" },
  { city: "Udaipur", state: "Tripura" },
  { city: "Dharmanagar", state: "Tripura" },
  { city: "Kailashahar", state: "Tripura" },
  { city: "Ambassa", state: "Tripura" },
  { city: "Khowai", state: "Tripura" },
  { city: "Belonia", state: "Tripura" },
  { city: "Sabroom", state: "Tripura" },
  { city: "Aizawl", state: "Mizoram" },
  { city: "Lunglei", state: "Mizoram" },
  { city: "Champhai", state: "Mizoram" },
  { city: "Mamit", state: "Mizoram" },
  { city: "Kolasib", state: "Mizoram" },
  { city: "Lawngtlai", state: "Mizoram" },
  { city: "Saiha", state: "Mizoram" },
  { city: "Serchhip", state: "Mizoram" },
  { city: "Mawkyrwat", state: "Meghalaya" },
  { city: "Tura", state: "Meghalaya" },
  { city: "Jowai", state: "Meghalaya" },
  { city: "Williamnagar", state: "Meghalaya" },
  { city: "Nongstoin", state: "Meghalaya" },
  { city: "Baghmara", state: "Meghalaya" },
  { city: "Resubelpara", state: "Meghalaya" },
  { city: "Ampati", state: "Meghalaya" },
  { city: "Haflong", state: "Assam" },

  // MP
  { city: "Gwalior", state: "Madhya Pradesh" },
  { city: "Datia", state: "Madhya Pradesh" },
  { city: "Shivpuri", state: "Madhya Pradesh" },
  { city: "Guna", state: "Madhya Pradesh" },
  { city: "Ashoknagar", state: "Madhya Pradesh" },
  { city: "Sagar", state: "Madhya Pradesh" },
  { city: "Tikamgarh", state: "Madhya Pradesh" },
  { city: "Niwari", state: "Madhya Pradesh" },
  { city: "Chhatarpur", state: "Madhya Pradesh" },
  { city: "Panna", state: "Madhya Pradesh" },
  { city: "Satna", state: "Madhya Pradesh" },
  { city: "Rewa", state: "Madhya Pradesh" },
  { city: "Mauganj", state: "Madhya Pradesh" },
  { city: "Sidhi", state: "Madhya Pradesh" },
  { city: "Singrauli", state: "Madhya Pradesh" },
  { city: "Shahdol", state: "Madhya Pradesh" },
  { city: "Anuppur", state: "Madhya Pradesh" },
  { city: "Umaria", state: "Madhya Pradesh" },
  { city: "Dindori", state: "Madhya Pradesh" },
  { city: "Mandla", state: "Madhya Pradesh" },
  { city: "Chhindwara", state: "Madhya Pradesh" },
  { city: "Pandhurna", state: "Madhya Pradesh" },
  { city: "Betul", state: "Madhya Pradesh" },
  { city: "Multai", state: "Madhya Pradesh" },
  { city: "Hoshangabad", state: "Madhya Pradesh" },
  { city: "Narmadapuram", state: "Madhya Pradesh" },
  { city: "Sehore", state: "Madhya Pradesh" },
  { city: "Raisen", state: "Madhya Pradesh" },
  { city: "Vidisha", state: "Madhya Pradesh" },
  { city: "Raisen", state: "Madhya Pradesh" },
  { city: "Rajgarh", state: "Madhya Pradesh" },
  { city: "Sehore", state: "Madhya Pradesh" },
  { city: "Khargone", state: "Madhya Pradesh" },
  { city: "Khandwa", state: "Madhya Pradesh" },
  { city: "Burhanpur", state: "Madhya Pradesh" },
  { city: "Nimach", state: "Madhya Pradesh" },
  { city: "Neemuch", state: "Madhya Pradesh" },
  { city: "Mandsaur", state: "Madhya Pradesh" },
  { city: "Ratlam", state: "Madhya Pradesh" },
  { city: "Dhar", state: "Madhya Pradesh" },
  { city: "Barwani", state: "Madhya Pradesh" },
  { city: "Alirajpur", state: "Madhya Pradesh" },
  { city: "Jhabua", state: "Madhya Pradesh" },
  { city: "Singrauli", state: "Madhya Pradesh" },
  { city: "Rewa", state: "Madhya Pradesh" },
  { city: "Satna", state: "Madhya Pradesh" },
  { city: "Maihar", state: "Madhya Pradesh" },
  { city: "Chitrakoot", state: "Madhya Pradesh" },
  { city: "Datia", state: "Madhya Pradesh" },
  { city: "Orchha", state: "Madhya Pradesh" },

  // Bihar / Jharkhand / Chhattisgarh / Odisha
  { city: "Gaya", state: "Bihar" },
  { city: "Bodh Gaya", state: "Bihar" },
  { city: "Nalanda", state: "Bihar" },
  { city: "Rajgir", state: "Bihar" },
  { city: "Bihar Sharif", state: "Bihar" },
  { city: "Muzaffarpur", state: "Bihar" },
  { city: "Darbhanga", state: "Bihar" },
  { city: "Madhubani", state: "Bihar" },
  { city: "Sitamarhi", state: "Bihar" },
  { city: "Purnia", state: "Bihar" },
  { city: "Kishanganj", state: "Bihar" },
  { city: "Araria", state: "Bihar" },
  { city: "Katihar", state: "Bihar" },
  { city: "Bhagalpur", state: "Bihar" },
  { city: "Banka", state: "Bihar" },
  { city: "Munger", state: "Bihar" },
  { city: "Begusarai", state: "Bihar" },
  { city: "Saharsa", state: "Bihar" },
  { city: "Supaul", state: "Bihar" },
  { city: "Madhepura", state: "Bihar" },
  { city: "Aurangabad", state: "Bihar" },
  { city: "Arwal", state: "Bihar" },
  { city: "Jehanabad", state: "Bihar" },
  { city: "Bhojpur", state: "Bihar" },
  { city: "Buxar", state: "Bihar" },
  { city: "Rohtas", state: "Bihar" },
  { city: "Sasaram", state: "Bihar" },
  { city: "Kaimur", state: "Bihar" },
  { city: "Bhabua", state: "Bihar" },
  { city: "Nawada", state: "Bihar" },
  { city: "Jamui", state: "Bihar" },
  { city: "Lakhisarai", state: "Bihar" },
  { city: "Sheikhpura", state: "Bihar" },
  { city: "Lohardaga", state: "Jharkhand" },
  { city: "Gumla", state: "Jharkhand" },
  { city: "Simdega", state: "Jharkhand" },
  { city: "Khunti", state: "Jharkhand" },
  { city: "West Singhbhum", state: "Jharkhand" },
  { city: "Chaibasa", state: "Jharkhand" },
  { city: "East Singhbhum", state: "Jharkhand" },
  { city: "Jamshedpur", state: "Jharkhand" },
  { city: "Bokaro", state: "Jharkhand" },
  { city: "Hazaribagh", state: "Jharkhand" },
  { city: "Ramgarh", state: "Jharkhand" },
  { city: "Koderma", state: "Jharkhand" },
  { city: "Chatra", state: "Jharkhand" },
  { city: "Latehar", state: "Jharkhand" },
  { city: "Palamu", state: "Jharkhand" },
  { city: "Medininagar", state: "Jharkhand" },
  { city: "Garhwa", state: "Jharkhand" },
  { city: "Deoghar", state: "Jharkhand" },
  { city: "Dumka", state: "Jharkhand" },
  { city: "Jamtara", state: "Jharkhand" },
  { city: "Sahebganj", state: "Jharkhand" },
  { city: "Pakur", state: "Jharkhand" },
  { city: "Godda", state: "Jharkhand" },
  { city: "Seraikela", state: "Jharkhand" },
  { city: "Jagdalpur", state: "Chhattisgarh" },
  { city: "Bastar", state: "Chhattisgarh" },
  { city: "Dantewada", state: "Chhattisgarh" },
  { city: "Kanker", state: "Chhattisgarh" },
  { city: "Kondagaon", state: "Chhattisgarh" },
  { city: "Narayanpur", state: "Chhattisgarh" },
  { city: "Sukma", state: "Chhattisgarh" },
  { city: "Bijapur", state: "Chhattisgarh" },
  { city: "Dhamtari", state: "Chhattisgarh" },
  { city: "Mahasamund", state: "Chhattisgarh" },
  { city: "Gariaband", state: "Chhattisgarh" },
  { city: "Balod", state: "Chhattisgarh" },
  { city: "Bemetara", state: "Chhattisgarh" },
  { city: "Mungeli", state: "Chhattisgarh" },
  { city: "Kawardha", state: "Chhattisgarh" },
  { city: "Kabirdham", state: "Chhattisgarh" },
  { city: "Rajnandgaon", state: "Chhattisgarh" },
  { city: "Khairagarh", state: "Chhattisgarh" },
  { city: "Durg", state: "Chhattisgarh" },
  { city: "Bhilai", state: "Chhattisgarh" },
  { city: "Korba", state: "Chhattisgarh" },
  { city: "Janjgir", state: "Chhattisgarh" },
  { city: "Champa", state: "Chhattisgarh" },
  { city: "Bilaspur", state: "Chhattisgarh" },
  { city: "Mungeli", state: "Chhattisgarh" },
  { city: "Kanker", state: "Chhattisgarh" },
  { city: "Puri", state: "Odisha" },
  { city: "Bhubaneswar", state: "Odisha" },
  { city: "Cuttack", state: "Odisha" },
  { city: "Rourkela", state: "Odisha" },
  { city: "Brahmapur", state: "Odisha" },
  { city: "Berhampur", state: "Odisha" },
  { city: "Sambalpur", state: "Odisha" },
  { city: "Puri", state: "Odisha" },
  { city: "Konark", state: "Odisha" },
  { city: "Jagatsinghpur", state: "Odisha" },
  { city: "Jajpur", state: "Odisha" },
  { city: "Bhadrak", state: "Odisha" },
  { city: "Balasore", state: "Odisha" },
  { city: "Baleshwar", state: "Odisha" },
  { city: "Mayurbhanj", state: "Odisha" },
  { city: "Baripada", state: "Odisha" },
  { city: "Kendujhar", state: "Odisha" },
  { city: "Keonjhar", state: "Odisha" },
  { city: "Sundargarh", state: "Odisha" },
  { city: "Jharsuguda", state: "Odisha" },
  { city: "Bargarh", state: "Odisha" },
  { city: "Bolangir", state: "Odisha" },
  { city: "Balangir", state: "Odisha" },
  { city: "Sonepur", state: "Odisha" },
  { city: "Subarnapur", state: "Odisha" },
  { city: "Nuapada", state: "Odisha" },
  { city: "Kalahandi", state: "Odisha" },
  { city: "Bhawanipatna", state: "Odisha" },
  { city: "Rayagada", state: "Odisha" },
  { city: "Gajapati", state: "Odisha" },
  { city: "Paralakhemundi", state: "Odisha" },
  { city: "Kandhamal", state: "Odisha" },
  { city: "Phulbani", state: "Odisha" },
  { city: "Nayagarh", state: "Odisha" },
  { city: "Khordha", state: "Odisha" },
  { city: "Angul", state: "Odisha" },
  { city: "Talcher", state: "Odisha" },
  { city: "Dhenkanal", state: "Odisha" },
  { city: "Ganjam", state: "Odisha" },
  { city: "Chatrapur", state: "Odisha" },

  // WB
  { city: "Howrah", state: "West Bengal" },
  { city: "Hooghly", state: "West Bengal" },
  { city: "Hugli", state: "West Bengal" },
  { city: "Chinsurah", state: "West Bengal" },
  { city: "Bandel", state: "West Bengal" },
  { city: "Serampore", state: "West Bengal" },
  { city: "Barrackpore", state: "West Bengal" },
  { city: "Naihati", state: "West Bengal" },
  { city: "Halisahar", state: "West Bengal" },
  { city: "Nabadwip", state: "West Bengal" },
  { city: "Krishnanagar", state: "West Bengal" },
  { city: "Berhampore", state: "West Bengal" },
  { city: "Baharampur", state: "West Bengal" },
  { city: "Malda", state: "West Bengal" },
  { city: "English Bazar", state: "West Bengal" },
  { city: "Raiganj", state: "West Bengal" },
  { city: "Balurghat", state: "West Bengal" },
  { city: "Cooch Behar", state: "West Bengal" },
  { city: "Jalpaiguri", state: "West Bengal" },
  { city: "Alipurduar", state: "West Bengal" },
  { city: "Darjeeling", state: "West Bengal" },
  { city: "Kalimpong", state: "West Bengal" },
  { city: "Siliguri", state: "West Bengal" },
  { city: "Kurseong", state: "West Bengal" },
  { city: "Asansol", state: "West Bengal" },
  { city: "Durgapur", state: "West Bengal" },
  { city: "Burdwan", state: "West Bengal" },
  { city: "Bardhaman", state: "West Bengal" },
  { city: "Bankura", state: "West Bengal" },
  { city: "Purulia", state: "West Bengal" },
  { city: "Midnapore", state: "West Bengal" },
  { city: "Medinipur", state: "West Bengal" },
  { city: "Kharagpur", state: "West Bengal" },
  { city: "Contai", state: "West Bengal" },
  { city: "Haldia", state: "West Bengal" },
  { city: "Tamluk", state: "West Bengal" },
  { city: "Bolpur", state: "West Bengal" },
  { city: "Shantiniketan", state: "West Bengal" },
  { city: "Bishnupur", state: "West Bengal" },
  { city: "Diamond Harbour", state: "West Bengal" },
  { city: "Baruipur", state: "West Bengal" },
  { city: "Canning", state: "West Bengal" },
  { city: "Basirhat", state: "West Bengal" },
  { city: "Bongaon", state: "West Bengal" },
  { city: "Habra", state: "West Bengal" },
  { city: "Ranaghat", state: "West Bengal" },
  { city: "Kalyani", state: "West Bengal" },
  { city: "Nabadwip", state: "West Bengal" },
  { city: "Santipur", state: "West Bengal" },
  { city: "Jiaganj", state: "West Bengal" },
  { city: "Murshidabad", state: "West Bengal" },
  { city: "Lalbagh", state: "West Bengal" },
  { city: "Nalhati", state: "West Bengal" },
  { city: "Rampurhat", state: "West Bengal" },
];
