import type { Product, Category, Brand } from "@/types";

export const mockCategories: Category[] = [
  {
    _id: "cat-1",
    name: "Electronics",
    slug: "electronics",
    description: "Electronic gadgets and devices",
    image: "/images/categories/electronics.jpg",
    productCount: 156,
    isActive: true,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-06-01T10:00:00Z",
    children: [
      {
        _id: "cat-1-1",
        name: "Smartphones",
        slug: "smartphones",
        description: "Mobile phones and accessories",
        parent: "cat-1",
        productCount: 89,
        isActive: true,
        createdAt: "2024-01-15T10:00:00Z",
        updatedAt: "2024-06-01T10:00:00Z",
      },
      {
        _id: "cat-1-2",
        name: "Laptops",
        slug: "laptops",
        description: "Laptops and notebooks",
        parent: "cat-1",
        productCount: 67,
        isActive: true,
        createdAt: "2024-01-15T10:00:00Z",
        updatedAt: "2024-06-01T10:00:00Z",
      },
    ],
  },
  {
    _id: "cat-2",
    name: "Fashion",
    slug: "fashion",
    description: "Clothing and accessories",
    image: "/images/categories/fashion.jpg",
    productCount: 234,
    isActive: true,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-06-01T10:00:00Z",
    children: [
      {
        _id: "cat-2-1",
        name: "Men's Clothing",
        slug: "mens-clothing",
        description: "Clothing for men",
        parent: "cat-2",
        productCount: 123,
        isActive: true,
        createdAt: "2024-01-15T10:00:00Z",
        updatedAt: "2024-06-01T10:00:00Z",
      },
      {
        _id: "cat-2-2",
        name: "Women's Clothing",
        slug: "womens-clothing",
        description: "Clothing for women",
        parent: "cat-2",
        productCount: 111,
        isActive: true,
        createdAt: "2024-01-15T10:00:00Z",
        updatedAt: "2024-06-01T10:00:00Z",
      },
    ],
  },
  {
    _id: "cat-3",
    name: "Home & Kitchen",
    slug: "home-kitchen",
    description: "Home appliances and kitchen essentials",
    image: "/images/categories/home-kitchen.jpg",
    productCount: 87,
    isActive: true,
    createdAt: "2024-02-10T10:00:00Z",
    updatedAt: "2024-06-01T10:00:00Z",
    children: [],
  },
  {
    _id: "cat-4",
    name: "Sports & Outdoors",
    slug: "sports-outdoors",
    description: "Sports equipment and outdoor gear",
    productCount: 45,
    isActive: false,
    createdAt: "2024-03-05T10:00:00Z",
    updatedAt: "2024-06-01T10:00:00Z",
    children: [],
  },
  {
    _id: "cat-5",
    name: "Books & Stationery",
    slug: "books-stationery",
    description: "Books, notebooks, and stationery items",
    productCount: 312,
    isActive: true,
    createdAt: "2024-01-20T10:00:00Z",
    updatedAt: "2024-06-01T10:00:00Z",
    children: [],
  },
];

export const mockBrands: Brand[] = [
  { _id: "brand-1", name: "Samsung", slug: "samsung", logo: "/images/brands/samsung.png", description: "Global electronics leader", productCount: 45, isActive: true },
  { _id: "brand-2", name: "Apple", slug: "apple", logo: "/images/brands/apple.png", description: "Premium technology products", productCount: 38, isActive: true },
  { _id: "brand-3", name: "Nike", slug: "nike", logo: "/images/brands/nike.png", description: "Athletic footwear and apparel", productCount: 67, isActive: true },
  { _id: "brand-4", name: "Adidas", slug: "adidas", logo: "/images/brands/adidas.png", description: "Sports and lifestyle brand", productCount: 54, isActive: true },
  { _id: "brand-5", name: "Prestige", slug: "prestige", logo: "/images/brands/prestige.png", description: "Kitchen appliances", productCount: 23, isActive: true },
  { _id: "brand-6", name: "boAt", slug: "boat", logo: "/images/brands/boat.png", description: "Audio and wearables", productCount: 31, isActive: false },
];

export const mockProducts: (Product & { seller: string; stockStatus: "in_stock" | "low_stock" | "out_of_stock" })[] = [
  {
    _id: "prod-1",
    name: "Samsung Galaxy S24 Ultra",
    slug: "samsung-galaxy-s24-ultra",
    description: "Premium flagship smartphone with S Pen and AI features",
    price: 134999,
    compareAtPrice: 149999,
    sku: "SAM-S24U-256",
    stock: 45,
    images: [
      { url: "/images/products/samsung-s24-1.jpg", alt: "Samsung Galaxy S24 Ultra", isPrimary: true },
      { url: "/images/products/samsung-s24-2.jpg", alt: "Samsung S24 Side", isPrimary: false },
    ],
    category: mockCategories[0].children![0],
    brand: mockBrands[0],
    variants: [
      { _id: "var-1", name: "256GB Titanium Black", sku: "SAM-S24U-256-BLK", price: 134999, stock: 15, attributes: { storage: "256GB", color: "Titanium Black" } },
      { _id: "var-2", name: "512GB Titanium Gray", sku: "SAM-S24U-512-GRY", price: 154999, stock: 30, attributes: { storage: "512GB", color: "Titanium Gray" } },
    ],
    tags: ["samsung", "smartphone", "flagship", "5g"],
    specifications: [
      { key: "Display", value: "6.8 inch QHD+ Dynamic AMOLED 2X" },
      { key: "Processor", value: "Snapdragon 8 Gen 3" },
      { key: "RAM", value: "12GB" },
    ],
    ratings: { average: 4.5, count: 1234 },
    isActive: true,
    isFeatured: true,
    isTrending: true,
    isBestSeller: false,
    createdAt: "2024-06-15T10:00:00Z",
    updatedAt: "2024-12-01T10:00:00Z",
    seller: "TechHub Electronics",
    stockStatus: "in_stock",
  },
  {
    _id: "prod-2",
    name: "Apple MacBook Air M3",
    slug: "apple-macbook-air-m3",
    description: "Ultra-thin laptop with M3 chip and all-day battery life",
    price: 114900,
    compareAtPrice: 129900,
    sku: "APL-MBA-M3-256",
    stock: 22,
    images: [
      { url: "/images/products/macbook-air-1.jpg", alt: "MacBook Air M3", isPrimary: true },
    ],
    category: mockCategories[0].children![1],
    brand: mockBrands[1],
    variants: [
      { _id: "var-3", name: "8GB/256GB Midnight", sku: "APL-MBA-M3-256-MID", price: 114900, stock: 12, attributes: { ram: "8GB", storage: "256GB", color: "Midnight" } },
      { _id: "var-4", name: "16GB/512GB Starlight", sku: "APL-MBA-M3-512-STA", price: 144900, stock: 10, attributes: { ram: "16GB", storage: "512GB", color: "Starlight" } },
    ],
    tags: ["apple", "laptop", "macbook", "m3"],
    specifications: [
      { key: "Chip", value: "Apple M3" },
      { key: "Display", value: "13.6 inch Liquid Retina" },
      { key: "Battery", value: "Up to 18 hours" },
    ],
    ratings: { average: 4.8, count: 892 },
    isActive: true,
    isFeatured: true,
    isTrending: false,
    isBestSeller: true,
    createdAt: "2024-03-10T10:00:00Z",
    updatedAt: "2024-11-15T10:00:00Z",
    seller: "Apple Authorized Store",
    stockStatus: "in_stock",
  },
  {
    _id: "prod-3",
    name: "Nike Air Max 270",
    slug: "nike-air-max-270",
    description: "Iconic lifestyle sneaker with Max Air unit",
    price: 13995,
    compareAtPrice: 15995,
    sku: "NIK-AM270-BLK-10",
    stock: 5,
    images: [
      { url: "/images/products/nike-am270-1.jpg", alt: "Nike Air Max 270", isPrimary: true },
    ],
    category: mockCategories[1].children![0],
    brand: mockBrands[2],
    variants: [
      { _id: "var-5", name: "Black/White UK 10", sku: "NIK-AM270-BLK-10", price: 13995, stock: 3, attributes: { size: "UK 10", color: "Black/White" } },
      { _id: "var-6", name: "Black/White UK 9", sku: "NIK-AM270-BLK-9", price: 13995, stock: 2, attributes: { size: "UK 9", color: "Black/White" } },
    ],
    tags: ["nike", "sneakers", "airmax", "lifestyle"],
    specifications: [
      { key: "Upper", value: "Mesh and synthetic" },
      { key: "Sole", value: "Rubber" },
    ],
    ratings: { average: 4.3, count: 2341 },
    isActive: true,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    createdAt: "2024-01-20T10:00:00Z",
    updatedAt: "2024-10-05T10:00:00Z",
    seller: "Nike Official Store",
    stockStatus: "low_stock",
  },
  {
    _id: "prod-4",
    name: "Prestige Iris 750W Mixer Grinder",
    slug: "prestige-iris-750w-mixer-grinder",
    description: "Powerful mixer grinder with 3 stainless steel jars",
    price: 2999,
    compareAtPrice: 4495,
    sku: "PRE-IRIS-750-SLV",
    stock: 78,
    images: [
      { url: "/images/products/prestige-mixer-1.jpg", alt: "Prestige Iris 750W", isPrimary: true },
    ],
    category: mockCategories[2],
    brand: mockBrands[4],
    variants: [
      { _id: "var-7", name: "Silver", sku: "PRE-IRIS-750-SLV", price: 2999, stock: 78, attributes: { color: "Silver" } },
    ],
    tags: ["prestige", "mixer", "grinder", "kitchen"],
    specifications: [
      { key: "Wattage", value: "750W" },
      { key: "Jars", value: "3 Stainless Steel Jars" },
      { key: "Warranty", value: "2 Years" },
    ],
    ratings: { average: 4.1, count: 5678 },
    isActive: true,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    createdAt: "2024-02-05T10:00:00Z",
    updatedAt: "2024-09-20T10:00:00Z",
    seller: "Home Appliances Hub",
    stockStatus: "in_stock",
  },
  {
    _id: "prod-5",
    name: "Adidas Ultraboost 23",
    slug: "adidas-ultraboost-23",
    description: "High-performance running shoes with Boost technology",
    price: 16999,
    sku: "ADI-UB23-WHT-10",
    stock: 0,
    images: [
      { url: "/images/products/adidas-ub23-1.jpg", alt: "Adidas Ultraboost 23", isPrimary: true },
    ],
    category: mockCategories[1].children![0],
    brand: mockBrands[3],
    variants: [
      { _id: "var-8", name: "White UK 10", sku: "ADI-UB23-WHT-10", price: 16999, stock: 0, attributes: { size: "UK 10", color: "White" } },
    ],
    tags: ["adidas", "running", "ultraboost"],
    specifications: [
      { key: "Upper", value: "Primeknit+" },
      { key: "Sole", value: "Boost" },
    ],
    ratings: { average: 4.6, count: 1234 },
    isActive: false,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    createdAt: "2024-04-10T10:00:00Z",
    updatedAt: "2024-08-15T10:00:00Z",
    seller: "Adidas Official Store",
    stockStatus: "out_of_stock",
  },
  {
    _id: "prod-6",
    name: "boAt Rockerz 450 Pro",
    slug: "boat-rockerz-450-pro",
    description: "Wireless on-ear headphones with 70H playback",
    price: 1799,
    compareAtPrice: 3990,
    sku: "BOA-R450P-BLK",
    stock: 156,
    images: [
      { url: "/images/products/boat-450-1.jpg", alt: "boAt Rockerz 450 Pro", isPrimary: true },
    ],
    category: mockCategories[0].children![0],
    brand: mockBrands[5],
    variants: [
      { _id: "var-9", name: "Black", sku: "BOA-R450P-BLK", price: 1799, stock: 89, attributes: { color: "Black" } },
      { _id: "var-10", name: "White", sku: "BOA-R450P-WHT", price: 1799, stock: 67, attributes: { color: "White" } },
    ],
    tags: ["boat", "headphones", "wireless", "bluetooth"],
    specifications: [
      { key: "Battery", value: "70 Hours Playback" },
      { key: "Driver", value: "40mm" },
      { key: "Bluetooth", value: "v5.3" },
    ],
    ratings: { average: 4.0, count: 8901 },
    isActive: true,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    createdAt: "2024-05-20T10:00:00Z",
    updatedAt: "2024-11-10T10:00:00Z",
    seller: "boAt Audio Store",
    stockStatus: "in_stock",
  },
];
