import type { Product, Review, Category } from "@/types";

export const MOCK_PRODUCT: Product = {
  _id: "prod-001",
  name: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
  slug: "sony-wh-1000xm5-wireless-headphones",
  description:
    "Industry-leading noise cancellation with Auto NC Optimizer. Crystal clear hands-free calling with 4 beamforming microphones. Up to 30 hours of battery life with quick charging (3 min charge for 3 hours of playback). Ultra-comfortable and lightweight design with soft fit leather. Multipoint connection lets you switch between two Bluetooth devices. Speak-to-Chat technology pauses music when you speak. Touch sensor controls for easy operation. Compatible with Sony Headphones Connect app for personalized settings.",
  price: 24990,
  originalPrice: 34990,
  images: [
    "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800",
    "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800",
    "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800",
    "https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?w=800",
  ],
  category: {
    _id: "cat-001",
    name: "Electronics",
    slug: "electronics",
  },
  brand: {
    _id: "brand-001",
    name: "Sony",
    slug: "sony",
  },
  rating: 4.5,
  numReviews: 2847,
  countInStock: 15,
  isFeatured: true,
  isDeal: false,
  variants: [
    {
      _id: "var-001",
      name: "Color",
      options: [
        { label: "Black", value: "black" },
        { label: "Silver", value: "silver" },
        { label: "Midnight Blue", value: "midnight-blue" },
      ],
    },
  ],
  specifications: {
    "Driver Size": "30mm",
    "Frequency Response": "4Hz - 40,000Hz",
    "Impedance": "48 ohms (1kHz)",
    "Bluetooth Version": "5.2",
    "Bluetooth Codecs": "SBC, AAC, LDAC",
    "Battery Life": "Up to 30 hours (NC ON)",
    "Charging Time": "Approx. 3.5 hours",
    Weight: "250g",
    "Noise Cancellation": "Dual Processor, 8 microphones",
    "NFC": "Yes",
    "Multipoint": "Yes (2 devices)",
    "Speak-to-Chat": "Yes",
    "Adaptive Sound Control": "Yes",
    Foldable: "No (Flat fold only)",
    "Carrying Case": "Included",
  },
  createdAt: "2025-01-15T10:30:00Z",
};

export const MOCK_REVIEWS: Review[] = [
  {
    _id: "rev-001",
    user: { _id: "u-001", name: "Rahul Sharma", avatar: null },
    rating: 5,
    title: "Best noise cancelling headphones I have ever used!",
    comment:
      "The noise cancellation on these is absolutely phenomenal. I use them daily on my commute and in the office. The sound quality is exceptional with deep bass and crystal clear highs. Battery easily lasts a full week of regular use. Comfortable enough to wear for hours without any discomfort. Worth every penny!",
    helpful: 234,
    createdAt: "2025-06-10T14:20:00Z",
  },
  {
    _id: "rev-002",
    user: { _id: "u-002", name: "Priya Patel", avatar: null },
    rating: 4,
    title: "Great sound, minor fit issue",
    comment:
      "Sound quality and ANC are top-notch. The multipoint connection is very useful for switching between laptop and phone. Only reason for 4 stars is that they can feel slightly tight after 3-4 hours of continuous use. Otherwise an excellent product.",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
    ],
    helpful: 156,
    createdAt: "2025-05-28T09:15:00Z",
  },
  {
    _id: "rev-003",
    user: { _id: "u-003", name: "Amit Kumar", avatar: null },
    rating: 5,
    title: "Perfect for work from home",
    comment:
      "These headphones have been a lifesaver for my work from home setup. The noise cancellation blocks out everything - my neighbor's construction noise, traffic, everything. Call quality is excellent too. My colleagues say I sound much clearer now compared to my old headset.",
    helpful: 98,
    createdAt: "2025-05-15T11:30:00Z",
  },
  {
    _id: "rev-004",
    user: { _id: "u-004", name: "Neha Gupta", avatar: null },
    rating: 3,
    title: "Good but expected more at this price",
    comment:
      "The sound quality is good but not as outstanding as I expected for this price point. ANC works well. The build quality feels premium. My previous Sennheiser had better bass response. Also, I wish they were foldable like the XM4.",
    helpful: 67,
    createdAt: "2025-04-20T16:45:00Z",
  },
  {
    _id: "rev-005",
    user: { _id: "u-005", name: "Vikram Singh", avatar: null },
    rating: 5,
    title: "Simply the best",
    comment:
      "Upgraded from XM4 and the improvement is noticeable. Better ANC, better call quality, and more comfortable fit. The new design is sleek and modern. Touch controls are intuitive. Highly recommended!",
    helpful: 45,
    createdAt: "2025-04-05T08:00:00Z",
  },
  {
    _id: "rev-006",
    user: { _id: "u-006", name: "Sneha Reddy", avatar: null },
    rating: 4,
    title: "Excellent for travel",
    comment:
      "Used these on a long flight and they performed beautifully. The ANC completely eliminated engine noise. Battery lasted the entire 14-hour flight withANC on. Very comfortable for extended wear.",
    helpful: 34,
    createdAt: "2025-03-22T13:10:00Z",
  },
  {
    _id: "rev-007",
    user: { _id: "u-007", name: "Arjun Nair", avatar: null },
    rating: 2,
    title: "Connectivity issues with Android",
    comment:
      "While the sound quality is great, I have been experiencing frequent Bluetooth disconnections with my Samsung Galaxy S24. Had to reset and re-pair multiple times. Sony support helped but the issue persists intermittently.",
    helpful: 89,
    createdAt: "2025-03-10T17:30:00Z",
  },
  {
    _id: "rev-008",
    user: { _id: "u-008", name: "Kavita Deshmukh", avatar: null },
    rating: 5,
    title: "Worth the splurge",
    comment:
      "Was hesitant about the price but after using them for 2 months, I can say it was worth every rupee. The sound quality, the silence, the comfort - everything is premium. The Speak-to-Chat feature is so convenient.",
    helpful: 28,
    createdAt: "2025-02-28T10:45:00Z",
  },
];

export const MOCK_RELATED_PRODUCTS: Product[] = [
  {
    _id: "prod-002",
    name: "JBL Tune 770NC Wireless Over-Ear Headphones",
    slug: "jbl-tune-770nc-headphones",
    description: "JBL Pure Bass Sound with Adaptive Noise Cancelling",
    price: 5999,
    originalPrice: 9999,
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400"],
    category: { _id: "cat-001", name: "Electronics", slug: "electronics" },
    brand: { _id: "brand-002", name: "JBL", slug: "jbl" },
    rating: 4.3,
    numReviews: 1523,
    countInStock: 25,
    isFeatured: false,
    isDeal: false,
    createdAt: "2025-02-10T10:00:00Z",
  },
  {
    _id: "prod-003",
    name: "boAt Rockerz 551 Over-Ear Bluetooth Headphones",
    slug: "boat-rockerz-551",
    description: "Bluetooth wireless headphones with 20H playtime",
    price: 1799,
    originalPrice: 3990,
    images: ["https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400"],
    category: { _id: "cat-001", name: "Electronics", slug: "electronics" },
    brand: { _id: "brand-003", name: "boAt", slug: "boat" },
    rating: 4.1,
    numReviews: 3456,
    countInStock: 50,
    isFeatured: false,
    isDeal: true,
    dealPrice: 1599,
    createdAt: "2025-01-20T10:00:00Z",
  },
  {
    _id: "prod-004",
    name: "Sennheiser HD 450BT Wireless Headphones",
    slug: "sennheiser-hd-450bt",
    description: "Active Noise Cancellation and Smart Pause",
    price: 9990,
    originalPrice: 14990,
    images: ["https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400"],
    category: { _id: "cat-001", name: "Electronics", slug: "electronics" },
    brand: { _id: "brand-004", name: "Sennheiser", slug: "sennheiser" },
    rating: 4.4,
    numReviews: 892,
    countInStock: 12,
    isFeatured: false,
    isDeal: false,
    createdAt: "2025-03-05T10:00:00Z",
  },
  {
    _id: "prod-005",
    name: "Audio-Technica ATH-M50xBT2 Wireless Headphones",
    slug: "audio-technica-ath-m50xbt2",
    description: "Legendary studio sound in a wireless design",
    price: 18990,
    originalPrice: 24990,
    images: ["https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?w=400"],
    category: { _id: "cat-001", name: "Electronics", slug: "electronics" },
    brand: { _id: "brand-005", name: "Audio-Technica", slug: "audio-technica" },
    rating: 4.6,
    numReviews: 456,
    countInStock: 8,
    isFeatured: false,
    isDeal: false,
    createdAt: "2025-04-01T10:00:00Z",
  },
  {
    _id: "prod-006",
    name: "Bose QuietComfort Ultra Headphones",
    slug: "bose-qc-ultra",
    description: "World-class noise cancellation with Immersive Audio",
    price: 29990,
    originalPrice: 37990,
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400"],
    category: { _id: "cat-001", name: "Electronics", slug: "electronics" },
    brand: { _id: "brand-006", name: "Bose", slug: "bose" },
    rating: 4.7,
    numReviews: 1234,
    countInStock: 6,
    isFeatured: false,
    isDeal: false,
    createdAt: "2025-05-01T10:00:00Z",
  },
  {
    _id: "prod-007",
    name: "Apple AirPods Max",
    slug: "apple-airpods-max",
    description: "High-fidelity audio with Active Noise Cancellation",
    price: 54900,
    originalPrice: 59900,
    images: ["https://images.unsplash.com/photo-1625245488600-f03fef636a3c?w=400"],
    category: { _id: "cat-001", name: "Electronics", slug: "electronics" },
    brand: { _id: "brand-007", name: "Apple", slug: "apple" },
    rating: 4.5,
    numReviews: 678,
    countInStock: 5,
    isFeatured: false,
    isDeal: false,
    createdAt: "2025-02-15T10:00:00Z",
  },
  {
    _id: "prod-008",
    name: "OnePlus Buds Pro 2",
    slug: "oneplus-buds-pro-2",
    description: "Smart ANC with Hi-Res sound quality",
    price: 8999,
    originalPrice: 11999,
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=400"],
    category: { _id: "cat-001", name: "Electronics", slug: "electronics" },
    brand: { _id: "brand-008", name: "OnePlus", slug: "oneplus" },
    rating: 4.2,
    numReviews: 2341,
    countInStock: 30,
    isFeatured: false,
    isDeal: false,
    createdAt: "2025-03-20T10:00:00Z",
  },
];

export const MOCK_SIMILAR_PRODUCTS: Product[] = [
  {
    _id: "prod-009",
    name: "Sony WH-1000XM4 Wireless Noise Cancelling Headphones",
    slug: "sony-wh-1000xm4",
    description: "Exceptional noise cancelling with premium sound",
    price: 19990,
    originalPrice: 29990,
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400"],
    category: { _id: "cat-001", name: "Electronics", slug: "electronics" },
    brand: { _id: "brand-001", name: "Sony", slug: "sony" },
    rating: 4.4,
    numReviews: 5678,
    countInStock: 20,
    isFeatured: false,
    isDeal: false,
    createdAt: "2024-11-10T10:00:00Z",
  },
  {
    _id: "prod-010",
    name: "Sony WF-1000XM5 Truly Wireless Earbuds",
    slug: "sony-wf-1000xm5",
    description: "Industry-leading noise cancellation in a compact design",
    price: 22990,
    originalPrice: 29990,
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=400"],
    category: { _id: "cat-001", name: "Electronics", slug: "electronics" },
    brand: { _id: "brand-001", name: "Sony", slug: "sony" },
    rating: 4.6,
    numReviews: 3210,
    countInStock: 18,
    isFeatured: false,
    isDeal: false,
    createdAt: "2025-01-05T10:00:00Z",
  },
  {
    _id: "prod-011",
    name: "Sony WH-CH720N Wireless Headphones",
    slug: "sony-wh-ch720n",
    description: "Lightweight noise cancelling headphones",
    price: 6990,
    originalPrice: 9990,
    images: ["https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400"],
    category: { _id: "cat-001", name: "Electronics", slug: "electronics" },
    brand: { _id: "brand-001", name: "Sony", slug: "sony" },
    rating: 4.2,
    numReviews: 1876,
    countInStock: 35,
    isFeatured: false,
    isDeal: false,
    createdAt: "2025-02-20T10:00:00Z",
  },
  {
    _id: "prod-012",
    name: "Sony WH-1000XM3 Wireless Headphones",
    slug: "sony-wh-1000xm3",
    description: "Digital Noise Cancelling with superior sound",
    price: 14990,
    originalPrice: 26990,
    images: ["https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?w=400"],
    category: { _id: "cat-001", name: "Electronics", slug: "electronics" },
    brand: { _id: "brand-001", name: "Sony", slug: "sony" },
    rating: 4.3,
    numReviews: 8923,
    countInStock: 10,
    isFeatured: false,
    isDeal: true,
    dealPrice: 13990,
    createdAt: "2023-08-15T10:00:00Z",
  },
];

export const MOCK_CATEGORIES: Category[] = [
  {
    _id: "cat-001",
    name: "Electronics",
    slug: "electronics",
    image: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400",
    productCount: 12453,
    children: [
      { _id: "cat-001-01", name: "Headphones", slug: "headphones", productCount: 3421 },
      { _id: "cat-001-02", name: "Speakers", slug: "speakers", productCount: 2134 },
      { _id: "cat-001-03", name: "Laptops", slug: "laptops", productCount: 1567 },
      { _id: "cat-001-04", name: "Smartphones", slug: "smartphones", productCount: 4532 },
      { _id: "cat-001-05", name: "Cameras", slug: "cameras", productCount: 799 },
    ],
  },
];

export const MOCK_FAQS = [
  {
    question: "What is the battery life of these headphones?",
    answer:
      "The Sony WH-1000XM5 offers up to 30 hours of battery life with noise cancelling turned on, and up to 40 hours with noise cancelling turned off.",
  },
  {
    question: "Are these headphones compatible with both Android and iOS?",
    answer:
      "Yes, the WH-1000XM5 is compatible with both Android and iOS devices via Bluetooth 5.2. The Sony Headphones Connect app is available on both platforms.",
  },
  {
    question: "Can I use them wired while the battery is dead?",
    answer:
      "Yes, you can use the included 3.5mm audio cable to listen passively even when the battery is completely drained.",
  },
  {
    question: "Do they support multi-device connection?",
    answer:
      "Yes, the WH-1000XM5 supports multipoint connection, allowing you to connect to two Bluetooth devices simultaneously and switch between them seamlessly.",
  },
  {
    question: "What is the warranty period?",
    answer:
      "The Sony WH-1000XM5 comes with a 1-year manufacturer warranty from the date of purchase.",
  },
  {
    question: "Are replacement ear pads available?",
    answer:
      "Yes, replacement ear pads are available through Sony authorized service centers and online.",
  },
];

export const MOCK_SPECIFICATIONS: Record<string, string> = {
  "Driver Type": "Closed Dynamic",
  "Driver Size": "30mm",
  "Frequency Response": "4Hz - 40,000Hz (LDAC, 990 kbps)",
  Sensitivity: "102 dB/mW",
  Impedance: "48 ohms (1kHz)",
  "Bluetooth Version": "5.2",
  "Bluetooth Range": "Up to 30 feet (10m)",
  "Bluetooth Codecs": "SBC, AAC, LDAC",
  "NFC": "Yes",
  "Battery Life (NC ON)": "Up to 30 hours",
  "Battery Life (NC OFF)": "Up to 40 hours",
  "Quick Charge": "3 min charge = 3 hours playback",
  "Charging Time": "Approx. 3.5 hours (full charge)",
  "Charging Connector": "USB Type-C",
  Weight: "250g",
  "Noise Cancellation": "Dual Processor with 8 microphones",
  "Ambient Sound Mode": "Yes",
  "Speak-to-Chat": "Yes",
  "Adaptive Sound Control": "Yes",
  "Multipoint Connection": "Yes (2 devices)",
  "Foldable": "No (Flat fold only)",
  "In the Box": "Headphones, USB-C cable, 3.5mm audio cable, Carrying case, Warranty card",
};
